### ISSUE TITLE
Use friendsofgo/errors instead of pkg/errors for go1.13 Unwrap support

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [newrelic/go-agent#107]
https://github.com/friendsofgo/errors/commit/d8ab995382e7324e457d27682d546863578c276f

**Comment by willnewrelic** [comment]
Hi @WIZARDISHUNGRY 

In an upcoming release, we are going to improve our handling errors due to the latest Go 1.13 changes!

We will also look into this https://github.com/friendsofgo/errors .  Thanks for bringing it to our attention.

**Comment by willnewrelic** [comment]
Hi @WIZARDISHUNGRY 

We just released agent version 2.14.0 with better support for Go 1.13's errors!

Take a look here:  https://github.com/newrelic/go-agent/blob/master/CHANGELOG.md#2140

Enjoy!
