### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by wayneashleyberry** [newrelic/go-agent#108]
Hi 👋 [golicense](https://github.com/mitchellh/golicense) couldn't detect the type of license used in this project, it tries to match against the [SPDX License List](https://spdx.org/licenses/). I had a quick look myself and also couldn't tell either, it might be worth mentioning which kind of license is actually being used on this project?

**Comment by willnewrelic** [comment]
Hi @wayneashleyberry 

The license is a proprietary license.  It does not conform to any open license standard.  Hope this helps!

**Comment by wayneashleyberry** [comment]
Yeah that helps a ton, thanks @willnewrelic!
