### ISSUE TITLE
External package support for payload parsing?

### ISSUE THREAD

**Issue by bernerdschaefer** [newrelic/go-agent#110]
We'd like to be able to better integrate NewRelic and OpenCensus into our stack. The [newrelic-opencensus-exporter-go](https://github.com/newrelic/newrelic-opencensus-exporter-go) is a helpful start for integrating the two, but only works when all components are using opencensus.

We, however, currently have components using NewRelic agents directly, but want to converge onto OpenCensus. There are some missing pieces to supporting this incremental state.

**Of course, if NewRelic agents propagated trace data in the [W3C TraceContext format](https://github.com/w3c/trace-context), it would be straightforward to wire everything up.**

Here's a minimal example demonstrating what we'd like to be able to support: accept incoming trace data in either W3C or NewRelic format and propagate with W3C format. It requires duplicating logic about the payload format and structure from internal packages. Credit to @purple4reina for getting me started on this code.

```go
package propagator

import (
	"encoding/json"
	"net/http"

	newrelic "github.com/newrelic/go-agent"
	"go.opencensus.io/trace"
	"go.opencensus.io/trace/propagation"
)

// Adaptor accepts either OpenCensus or NewRelic HTTP request span context data
// but always propagates outgoing requests in OpenCensus format. Use like:
//
//   h := ochttp.Handler{
//      Propagation: Adaptor{Propagation: tracecontext.HTTPFormat{}},
//      Handler: mux,
//   }
type Adaptor struct {
	Propagation propagation.HTTPFormat
}

var _ propagation.HTTPFormat = Adaptor{}

// SpanContextFromRequest extracts SpanContext from an incoming request. It
// attempts to derive the context from the configured OpenCensus Propagation
// format and falls back to NewRelic.
func (a Adaptor) SpanContextFromRequest(req *http.Request) (trace.SpanContext, bool) {
	if sc, ok := a.Propagation.SpanContextFromRequest(req); ok {
		return sc, ok
	}

	header := req.Header.Get(newrelic.DistributedTracePayloadHeader)
	if header == "" {
		return trace.SpanContext{}, false
	}

	// Would prefer to be able to use internal.AcceptPayload(header) rather than
	// re-implement its data format and logic (e.g., this is missing version
	// checking). This is the most minimal amount of duplication possible,
	// but still risks drift or missing features!
	var payload struct {
		Data struct {
			GUID    string `json:"id"`
			TraceID string `json:"tr"`
		} `json:"d"`
	}
	if err := json.Unmarshal([]byte(header), &payload); err != nil {
		return trace.SpanContext{}, false
	}

	return &trace.SpanContext{
		TraceID: payload.Data.TraceID,
		SpanID:  payload.Data.GUID,
	}, true
}

// SpanContextToRequest sets outgoing trace headers on req using the configured
// OpenCensus Propagation format.
func (a Adaptor) SpanContextToRequest(sc trace.SpanContext, req *http.Request) {
	return a.Propagation.SpanContextToRequest(sc, req)
}
```

It would be helpful to have access to this payload definition and parsing code, which currently only exists in `internal` with `internal.AcceptPayload` and `internal.Payload`, so we don't have to duplicate effort here!

**Comment by purple4reina** [comment]
@bernerdschaefer,

Thanks so much for the detailed explanation and example!

It is our intent to add support for W3C headers (both send and receive) from our Go Agent. It is currently on our road map.

Rather than making `internal.AcceptPayload` method public, I'd suggest waiting until we have released W3C header support. This will allow our agent to keep a smaller API footprint and allow you to not have to do any of the hard work in sending/receiving headers between your applications.

I will respond again to this issue once we have released. However, in the meantime let us know if there's any more we can do to help you out!

**Comment by purple4reina** [comment]
Hey @bernerdschaefer!

We are very pleased to announce the release of Go Agent v3.1.0 which includes support for W3C Trace Context! Check it out! As of today, as long as your applications that are using the Go Agent have distributed tracing enabled, they will be able to accept incoming W3C headers. They will also emit outgoing W3C headers that your OpenCensus application will be able to successfully read! You'll then get some amazing Distributed Traces in the UI! 🎉 🙌

**Comment by bernerdschaefer** [comment]
@purple4reina that's great news, thanks!
