### ISSUE TITLE
Should the nrhttprouter automatically inject txn into the Context?

### ISSUE THREAD

**Issue by flaviotruzzi** [newrelic/go-agent#112]
The documentation says that for systems using `http` based configuration we would need to use `newrelic.WrapHandleFunc`, when using an integration like nrhttprouter.

Shouldn't this be done by the integration itself, otherwise we need to either add the `WrapHandleFunc` or create a middleware that will do that and create the newrelic transactions, which remove the purpose of the integration itself.

If you agree I have a small branch ready on my fork.

**Comment by willnewrelic** [comment]
Hi @flaviotruzzi 

Yes, if you are using `nrhttprouter`, then there is no reason to use `newrelic.WrapHandleFunc` or `newrelic.WrapHandle`!

We will improve the documentation of `WrapHandleFunc` and `WrapHandle` to make this more clear.

Thanks for writing in!

**Comment by flaviotruzzi** [comment]
Not sure if you would like, but you can use this if you want https://github.com/newrelic/go-agent/compare/master...flaviotruzzi:inject-context?expand=1

**Comment by willnewrelic** [comment]
Hi @flaviotruzzi !

Good catch:  We are not adding the transaction to the request.  We should be!

Thank you for the commit.  We will fix this mistake for the next release.

**Comment by flaviotruzzi** [comment]
Should I open a PR, or you plan to deal with this differently?

**Comment by willnewrelic** [comment]
Hi @flaviotruzzi 

I have made an issue in our internal bug tracker.  We will make a PR.  We appreciate you bringing this to our attention!

**Comment by adimarco** [comment]
What is the recommended way of dealing with this while we wait for the bugfix?

**Comment by willnewrelic** [comment]
Hi @adimarco !  We expect to release later this week.
