### ISSUE TITLE
Question about StartTransaction without http.ResponseWriter and http.Request

### ISSUE THREAD

**Issue by lpy-neo** [newrelic/go-agent#115]
config := newrelic.NewConfig("myappname", "mykey")
  app, err := newrelic.NewApplication(config)
  transaction = app.StartTransaction("/lesson", nil, nil)
  _ = transaction.NoticeError(errToReport)
  transaction.End()

I've tried above code, but it does not work? Why?
NoticeError returns nil, but I didn't seen any error report.

The above code works if I replace `transaction` with the return value of newrelic.FromContext(ctx).

**Comment by newrelic-eheinlein** [comment]
Hi @lpy-neo ! For questions like this with the agent we generally recommend working with our Support team, which can be reached directly though support.newrelic.com.
