### ISSUE TITLE
PrepareNamedContext broken with nrpq/sqlx

### ISSUE THREAD

**Issue by adimarco** [newrelic/go-agent#117]
When using `nrpq` as a postgres driver, running `PrepareNamedContext()` with `sqlx` is broken.

Tracing through the underlying code, sqlx can't figure out a `BindType` for the driver string `"nrpostgres"` - https://github.com/jmoiron/sqlx/blob/master/bind.go#L24

A PR has already been opened with `sqlx` to support this - https://github.com/jmoiron/sqlx/pull/563 - but you might want to note in the documentation that this integration doesn't work until it's merged.

**Comment by purple4reina** [comment]
Hey @adimarco!

Thanks a ton for opening this issue. I believe we may have already address your concerns in this earlier issue https://github.com/newrelic/go-agent/issues/116. Check it out!

Let me know if you have further questions after reading it. Always happy to help out!

**Comment by adimarco** [comment]
Thanks @purple4reina  - that's the same issue.
