### ISSUE TITLE
Set HostDisplayName automatically on Heroku

### ISSUE THREAD

**Issue by edmorley** [newrelic/go-agent#119]
Hi!

The New Relic agents for other languages automatically configure the host display name based on the presence of the environment variable `DYNO` ([Heroku env vars](https://devcenter.heroku.com/articles/dynos#local-environment-variables)). They also automatically shorten the `run.*` and `scheduler.*` dyno names (since these are randomly generated).

For example:
* Ruby agent:
  - https://github.com/newrelic/rpm/blob/418d9b854b4e65cddd9dbd10a4bc55cb4ceb5eb3/lib/new_relic/agent/hostname.rb#L10-L17
  - https://github.com/newrelic/rpm/blob/418d9b854b4e65cddd9dbd10a4bc55cb4ceb5eb3/lib/new_relic/agent/configuration/default_source.rb#L1457-L1458
* Python agent:
  - https://github.com/edmorley/newrelic-python-agent/blob/d624adc51788d4e95a4a0e136f8ec290c61607a1/newrelic/newrelic/common/system_info.py#L335-L344
  - https://github.com/edmorley/newrelic-python-agent/blob/0417186a391c3b3289925b697be9e5c33f903d4a/newrelic/newrelic/core/config.py#L629-L630

Would it be possible to support this in the Go agent too, to save having to add boilerplate for this in each of our apps that uses the agent?

Many thanks,

Ed

**Comment by edmorley** [comment]
In fact, even if I set `HostDisplayName` manually myself, it looks like the Go agent behaves differently to the other agents, in that the raw hostname still appears in the APM UI's hosts section on the "Overview" page, rather than the `DYNO` name.

For example:

![Screenshot_2019-11-29 release-dyno-watcher - staging - New Relic](https://user-images.githubusercontent.com/501702/69876301-29556980-12b7-11ea-9866-82b3c2c67820.png)

The DYNO name does appear in the servers menu however.

**Comment by willnewrelic** [comment]
Hi @edmorley !

Thanks for bringing this to our attention!  I have begun investigating this behavior of the other agents, and will keep you updated with our plans: Most likely we match their behavior, but I can't promise that yet!  In any case, we want to have a great Heroku experience!

**Comment by edmorley** [comment]
@willnewrelic thank you :-)

Just to expand on https://github.com/newrelic/go-agent/issues/119#issuecomment-559812922 slightly (ie when using a manually set `HostDisplayName`), one of the problems is that the APM transactions view quickly gets slow to load/unwieldy due to the number of hosts (when they would otherwise be consolidated, if mapped to the dyno name):

![Screenshot_2019-12-05 Transactions - release-dyno-watcher - staging - New Relic](https://user-images.githubusercontent.com/501702/70253752-b5fe9c80-177b-11ea-8437-b5c158ff1984.png)

(We have apps that have hundreds more shown)

**Comment by edmorley** [comment]
I've tried also setting `Utilization.BillingHostname` in addition to `DisplayName`, however I still get the mass of `dyno-*` hosts seen above.

**Comment by purple4reina** [comment]
@edmorley The other language agents use the `DYNO` environment variable to replace the value they get for `hostname`. This value isn't something that can be overwritten with a configuration. We're working on an internal pull request now to fix this.

The change will be that in this `sysinfo.Hostname` method we will first check for the `DYNO` env var, then reach out to the os for the hostname.

https://github.com/newrelic/go-agent/blob/d01b4de3d68ee9fd20da42ed57fa2e888eb3140b/v3/internal/sysinfo/hostname_linux.go#L9

**Comment by edmorley** [comment]
Awesome, thank you :-)

**Comment by willnewrelic** [comment]
Hi @edmorley 

The 3.0.0 agent now responds to the `DYNO` environment variable!

**Comment by edmorley** [comment]
Thank you! :-)

I spotted one tiny thing - with the current implementation `getDynoName()` checks for the exact prefix (eg `run`) rather than `run.`, so for an input of `runsomeotherprocess.1` will output `run.*` rather than leaving it unadjusted. The Ruby agent appends the period before comparing the strings:
https://github.com/newrelic/rpm/blob/7bb753161cf0215a09fd609f39b5a859a9860f49/lib/new_relic/agent/hostname.rb#L29
(Albeit the Python agent [doesn't](https://github.com/edmorley/newrelic-python-agent/blob/d624adc51788d4e95a4a0e136f8ec290c61607a1/newrelic/newrelic/common/system_info.py#L341), so has the same behaviour/issue as `getDynoName()`)

**Comment by purple4reina** [comment]
@edmorley Good point. Our internal specification for this feature doesn't clarify this. I just copied the Python implementation and went with that. We'll go ahead and make the change and release it with our next agent version.

Thanks again!!!
