### ISSUE TITLE
Document using NewRequestWithContext with NewRoundTripper

### ISSUE THREAD

**Issue by edmorley** [newrelic/go-agent#121]
Hi

I've been adding the New Relic Go agent to some of our legacy Go apps, which didn't previously make use of contexts - and so weren't specifying a context when creating `http.Request`s.

Rather than passing `newrelic.Transactions` around, it seemed cleaner to make use of `newrelic.NewContext()` and pass around `context.Context`s containing the transaction throughout the app instead.

The `newrelic.NewRoundTripper` docs give an example that uses `newrelic.RequestWithTransactionContext(request, txn)`, which initially led me to me doing something like:

```go
func Foo(ctx context.Context, ...) {
	txn := newrelic.FromContext(ctx)
	defer txn.StartSegment("Foo").End()

	req, err := http.NewRequest("GET", url, nil)
	// ...
	request = newrelic.RequestWithTransactionContext(request, txn)
	// ...
}
```

...when this would have been cleaner (and also meant the http request had the full context, allowing for future optimisations like context cancellation/timeout cleaning up the http request properly etc):

```go
func Foo(ctx context.Context, ...) {
	txn := newrelic.FromContext(ctx)
	defer txn.StartSegment("Foo").End()

	req, err := http.NewRequestWithContext(ctx, "GET", url, nil)
	// ...
}
```

Whilst in retrospect this second form is obvious (and for non-legacy apps already using best practices around http requests and context cancellation etc this scenario is less likely to occur), I think it would be useful to add an example using `NewRequestWithContext` to the `newrelic.NewRoundTripper` docs :-)

**Comment by purple4reina** [comment]
Thanks for this suggestion @edmorley ! We're really loving exploring along with you how the API could be improved.

We're going to contemplate this suggestion a bit. We'll get the v3.0 release out the door first then circle back to this. As we come up with ideas, we'll share them with you here.

As one aside though, I do believe it is still possible to create a request with a cancellation/timeout _and_ the transaction in the context. You'd have to call `RequestWithTransactionContext` _and_ `req.WithContext`.

```go
ctx, cancel := context.WithTimeout(context.Background(), 50*time.Millisecond)
defer cancel()

req, err := http.NewRequest("GET", url, nil)
// ...
req = req.WithContext(ctx)
req = newrelic.RequestWithTransactionContext(req, txn)
```

A bit much, but it's possible.

**Comment by willie** [comment]
@edmorley Thanks for writing up your example. This explained the usage of `newrelic.NewRoundTripper` to me much better than the docs. I feel a lot better about the overhead of integrating New Relic as a result. (My code base is pretty old and much predates `http.NewRequestWithContext`.)
