### ISSUE TITLE
Debugging "unable to end segment" errors

### ISSUE THREAD

**Issue by edmorley** [newrelic/go-agent#122]
After adding the agent to a legacy Go project, we're seeing a number of errors of form:
* `level=error msg="unable to end segment" component=newrelic reason="transaction has already ended"`
* `level=error msg="unable to end external segment" component=newrelic reason="transaction has already ended"`

The project in question makes heavy use of goroutines, and from code inspection I was able to spot some cases where goroutines / http requests within them weren't cleaned up explicitly (causing the `txn.End()` to be reached before other goroutines had finished their `newrelic.NewRoundTripper`-using http requests).

However even after fixing some of the obvious cases, I'm still seeing these errors.

In order to debug this more easily, I was wondering if it would be possible to add the segment name to the error msg/reason/... so I can work out where the races are occurring?

**Comment by purple4reina** [comment]
> In order to debug this more easily, I was wondering if it would be possible to add the segment name to the error msg/reason/... so I can work out where the races are occurring?

This is a great idea! Thanks for the suggestion. We'll get the change out as soon as we can.

**Comment by purple4reina** [comment]
@edmorley We've released v3.0.0 with better debug logging as you've requested! Let us know if that helps you out!

**Comment by edmorley** [comment]
Thank you!
