### ISSUE TITLE
Race condition when hostname set from DYNO environment variable

### ISSUE THREAD

**Issue by edmorley** [newrelic/go-agent#127]
Hi

In v3.0.0 of the agent, the host name reported to New Relic is calculated from either the environment variable `DYNO` (if found) or else `os.Hostname()`:
https://github.com/newrelic/go-agent/blob/v3.0.0/v3/internal/sysinfo/hostname.go#L9-L37

In one of our apps, I noticed that the APM transactions view was displaying a proportion of transactions as having the hostname from `os.Hostname()` rather than that from `DYNO`.

Shortly after startup, this app sanitizes the environment (using `os.Unsetenv()` to unset any env var that's not `PATH`, `LANG`, `HOME`) prior to invoking additional processes, to prevent unintended side-effects.

This led me to suspect that the Go agent's hostname calculation was racing with the startup env var sanitization. This was confirmed by temporarily adding `DYNO` to the sanitization whitelist, at which point the hostname was consistently reported by all jobs to be the value from `DYNO`.

The app uses `WaitForConnection()` (set to 5 seconds) prior to the env var sanitization step, however this does not help.

It looks like the hostname is actually calculated twice:
https://github.com/newrelic/go-agent/blob/v3.0.0/v3/newrelic/app_run.go#L108
https://github.com/newrelic/go-agent/blob/v3.0.0/v3/internal/utilization/utilization.go#L210

Is the `utilization.go` instance (which as far as I can tell occurs async on another goroutine) overwriting the initial value calculated by the `app_run.go` invocation? Whilst our scenario (clearing env vars some time after initial startup) is possibly a bit niche, it doesn't feel quite right for the hostname to be able to change once the agent is already running/registered.

**Comment by willnewrelic** [comment]
Hi @edmorley 

Thanks for bringing this to our attention.  We are taking a look!

**Comment by willnewrelic** [comment]
Hi @edmorley 

This will be fixed in the next release:  We will not try to access the `DYNO` environment variable after `NewApplication` has returned.

**Comment by edmorley** [comment]
Awesome, thank you :-)

**Comment by purple4reina** [comment]
Hey @edmorley, we just released v3.1.0 that includes this fix. Thanks again!

**Comment by edmorley** [comment]
Thank you!
