### ISSUE TITLE
Support for expected errors

### ISSUE THREAD

**Issue by ronny** [newrelic/go-agent#128]
AFAIK, there is no support for [expected errors](https://docs.newrelic.com/docs/agents/manage-apm-agents/agent-data/manage-errors-apm-collect-ignore-or-mark-expected#expected) in the Go agent. Is this something that's planned? Any estimates/milestones for it? Thanks.

**Comment by newrelic-eheinlein** [comment]
Thank you for your interest!  We have added this request to our backlog, and if/when it is released, we will let you know.

**Comment by jodeev** [comment]
I'm going to close this for now.  As noted, we've added this to our backlog. We would definitely like to know whether others also need this, so please add a comment if you are also interested. This will help us prioritize work.
