### ISSUE TITLE
SameSite Cookie Warning

### ISSUE THREAD

**Issue by lovestulip** [newrelic/go-agent#129]
Doing an audit of some of our Go WordPress websites, we are seeing this warning pop up in Chrome Console:

`A cookie associated with a cross-site resource at https://nr-data.net/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032. `

This should be solvable by setting `SameSite:None` on those cookies and setting the `secure` attribute on the cookie ( meaning it will only be usable over HTTPS ).

More on this with Chrome 80's upcoming release here: https://www.chromestatus.com/features/schedule

**Comment by willnewrelic** [comment]
Hi @lovestulip 

Sorry something is going wrong!  We don't understand how the Go agent is involved with your issue.  Would you mind giving us some more information about how you are using the Go agent?  We think it is possible that a cookie or Javascript issue could be the result of using our browser monitoring product.  Perhaps you are using that?

**Comment by lovestulip** [comment]
Hi @willnewrelic! Ah I believe you are correct! Apologies for the confusion. [On VIP Go, New Relic is available](https://wpvip.com/documentation/vip-go/new-relic-on-vip-go/) for clients on our platform, they can use it to monitor the PHP (WordPress) code and browser performance of websites and applications.

I think this warning stems from the browser monitoring product. My apologies, I think I am in the wrong place! 

> We think it is possible that a cookie or Javascript issue could be the result of using our browser monitoring product. Perhaps you are using that?

Thanks for pointing me in the right direction. I'll circle back with my wider team and, if needed, open a support ticket here: https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/find-help-use-support-portal#support_tickets

**Comment by lovestulip** [comment]
Hi again! Doing some more digging, I see a number of New Relic users have reached out to support on the[ same message in Chrome warning regarding SameSite cookies](https://discuss.newrelic.com/t/chrome-warning-for-cookie-samesite-attribute/84976/16). The latest reply (11 days ago) is:

> We do intend to have a fix for this implemented before the Chrome update is released publicly, and at this time we are not expecting this to require customers to update their agent.

All this to say, thanks again! I'll close this issue out! Again sorry for my confusion.
