### ISSUE TITLE
Get Transaction from Transaction?

### ISSUE THREAD

**Issue by samv** [newrelic/go-agent#13]
Hi,

I've built a system around context.Context to pass down the newrelic Transaction to various call stacks, but now the problem I'm facing is that I hit a code block which spawns a goroutine, and that goroutine inherits the context.  I want to create a new newrelic.Transaction for it, but all I have is the Transaction, not the app.  So far I've got through this without creating my own tracing wrapper package, but now I'll have to in order to store the global Application instance (which is currently created in my 'main' and so not importable anywhere).

It would be nice if it were possible to access the equivalent of Application.StartTransaction from another Transaction object, specifically for the case of goroutines.  I'm just going to have to disable tracing for this goroutine in the meantime.

I thought you might be interested in this API design feedback, but it's not critical for me.

**Comment by willnewrelic** [comment]
Hi samv

Thanks for the idea. I'm going to leave this open and add the "track-interest" label. I encourage all who would like this change to add a comment or thumbs up.

**Comment by belimawr** [comment]
I also would like this feature. I had a similar issue, and solved this by creating my own http handler wrapper that adds the newrelic transaction and app on context.

**Comment by astormnewrelic** [comment]
@samv, @belimawr Thanks both for the feature request/feedback!  We're still thinking of the best way to handle this use case in the go-agent, or if its something we should leave for application/system developers to do on their own (i.e. @belimawr's handler wrapper).  

We've got a feature request open for this internally, and we're going to close this issue out for now.  If you have additional thoughts please don't hesitate to keep the conversation going. Thanks again for your feedback, and for using the New Relic Go Agent.

**Comment by willnewrelic** [comment]
Hi @samv !

In recent release 2.4 we have added an `Application()` method to the transaction:
https://github.com/newrelic/go-agent/blob/master/CHANGELOG.md#240

This let's you start a new transaction using a transaction:

```go
newTxn := txn.Application().StartTransaction("newTxn", nil, nil)
```

I hope this helps!
