### ISSUE TITLE
upgrade v3/integrations/nrgrpc to use v1.3.1 of protobuf

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#130]
The only real difference between v1.3.0 and v1.3.1 is that they removed all the dependencies from their go.mod file. Please change your go.mod file to reference v1.3.1 so that use of this library does not control the version of genproto that gets selected.

**Comment by purple4reina** [comment]
@rittneje,

Thanks for submitting this issue. You are correct that protobuf cleaned up their go.mod file between v1.3.0 and v1.3.1 in https://github.com/golang/protobuf/pull/805 and https://github.com/golang/protobuf/pull/808.

We'll make this change our our go.mod file and get it out with our next release.

Rey

**Comment by willnewrelic** [comment]
Hi @rittneje

We just released `v3/integrations/nrgorilla/v1.1.0` which should have solved this issue!  Thanks for bringing this to our attention.

**Comment by rittneje** [comment]
Awesome, thank you! I can confirm that the issue is fixed.
