### ISSUE TITLE
Emit newrelic.MessageProducerSegment for SQS and SNS calls in the AWS SDK

### ISSUE THREAD

**Issue by v3n** [newrelic/go-agent#136]
Would be nice for the integration to automatically handle all of this. They currently show up as HTTP requests which skew our APM telemetry for our mixed queue and http-based services.

**Comment by newrelic-eheinlein** [comment]
Thank you for this suggestion! We will look into this and see if we can add this to our roadmap.

**Comment by jodeev** [comment]
I've made sure to put this in our backlog. I expect that we will get to this in a future release.

We would definitely like to know how many others also need this, so please add a comment if you are also interested.   We always welcome PRs as well.
