### ISSUE TITLE
Orphaned service transactions in distributed traces

### ISSUE THREAD

**Issue by larsinmar** [newrelic/go-agent#139]
We have been seeing orphaned service transactions maybe half the time:

![image](https://user-images.githubusercontent.com/16964445/77351148-c1b6a480-6d13-11ea-8ba4-3092a07d7e08.png)

These orphaned spans happen intermittently, and we've noticed that they only occur when the timestamp is different than the associated root span.  The difference is always an off by one, and it appears to be related to how the time is being transmitted for transactions vs spans:

https://github.com/newrelic/go-agent/blob/de0daeceb386cd36dffa4b0d288886f672402196/internal/span_events.go#L50

vs

https://github.com/newrelic/go-agent/blob/de0daeceb386cd36dffa4b0d288886f672402196/internal/txn_events.go#L26

Because they round differently, I believe this is causing mismatches.

As an example, after a few runs we saw a mismatch where two times were transmitted for transaction and span respectively:

  1584988082.8955681
  1584988082895

In the New Relic UI, it reported an orphaned span and showed these timestamps for the transaction and span respectively:
  1584988082896
  1584988082895
 
Looks like it's been working this way for a while in the client so not sure if this is a longstanding issue or something caused by an external change.

**Comment by purple4reina** [comment]
@larsinmar Thanks a ton for opening this issue. Orphaned spans have been top of my mind recently, especially since issue https://github.com/newrelic/go-agent/issues/138 was also opened this week.

Before we proceed, I'd like to gather a bit more info about your application. Honestly I'm dubious about the timestamp being the cause of your orphans. The Distributed Tracing UI relies on the `parentId` attribute in order to place it in the waterfall. If the guid listed in the `parentId` attribute isn't found, then the span is shown as "orphaned".

Common causes for this are:
* Ending a segment _after_ the transaction has ended. This can be a commonly unnoticed occurrence when using the `txn.NewGoroutine` api.
* Forgetting to call `End()` on a running segment.

Both of these situations will mean that a span is not recorded and sent to the backend. So, while the _agent_ knows about the span, the _backend_ won't.

While debugging issue https://github.com/newrelic/go-agent/issues/138, we discovered that in certain cases when using the `nrmysql` driver segments don't get ended. Maybe this is the cause for your orphans as well?

Thanks again and any more details you can give about your application will be super helpful. I'm looking forward to getting to a working solution!

Rey

**Comment by larsinmar** [comment]
I believe End() is being called in each case, the inner part of the middleware for our requests looks like this:

`txn := *newRelicApp.StartTransaction(pathTemplate)
					defer txn.End()
					txn.SetWebRequestHTTP(r)
					writer := txn.SetWebResponse(w)
					next.ServeHTTP(writer, newrelic.RequestWithTransactionContext(r, &txn))`
 
And in all the examples I'm looking at right now, there are no segments.  There aren't any parentIds either (at least not looking in insights and either of the span attributes).  

If I'm querying a non-orphaned example:

If I query * from the Span table for the trace ID, I'll get a single span, that looks like this:

Timestamp,App ID,App Name,Category,Container ID,Duration,Entity.GUID,Entity.Name,Entity GUID,GUID,Host,Name,Priority,Real Agent ID,Sampled,Service.Name,Trace.ID,Trace ID,Transaction ID
2020-03-24 13:20:40,[appId],[app],generic,c50d572ef6160c95b68bc79300fe276dc664cf6975fdf1c05cd3b83260458c73,0.0226733,MjU5ODc5MXxBUE18QVBQTElDQVRJT058NjE1NzE2MDM3,[app],MjU5ODc5MXxBUE18QVBQTElDQVRJT058NjE1NzE2MDM3,08c030c6ad9d66aa,c50d572ef616,[name],1.845688,[agent],true,[app],11f88d81590f3717dfd3b5d13d86f820,11f88d81590f3717dfd3b5d13d86f820,11f88d81590f3717


Querying * from the transaction table, I get something like this:

Timestamp,App ID,App Name,Container ID,Duration,Entity GUID,Error,GUID,Host,Http.Status Code,Http Response Code,Name,Priority,Real Agent ID,Request.Headers.Accept,Request.Method,Request.URI,Response.Headers.Content Type,Sampled,Total Time,Trace ID,Transaction Sub Type,Transaction Type
2020-03-24 13:20:40,[appId],[app],c50d572ef6160c95b68bc79300fe276dc664cf6975fdf1c05cd3b83260458c73,0.0226733,MjU5ODc5MXxBUE18QVBQTElDQVRJT058NjE1NzE2MDM3,false,11f88d81590f3717,c50d572ef616,200,200,[name],1.845688,639297296,application/json,GET,[path],application/json; charset=UTF-8,true,0.0226733,11f88d81590f3717dfd3b5d13d86f820,Go,Web


As far as I can tell, the transaction and the span are identical in basically every respect. The transaction entry and the span entry correspond with the two "spans" in the UI.

For an orphaned version, if I query * from the span table for that traceId I get:

Timestamp,App ID,App Name,Category,Container ID,Duration,Entity.GUID,Entity.Name,Entity GUID,GUID,Host,Name,Priority,Real Agent ID,Sampled,Service.Name,Trace.ID,Trace ID,Transaction ID
2020-03-24 13:02:50,[appId],[app],generic,5774e88bb114c7157e0cfdab1e8150dfc58fe03c8e23ca7376fdd860795d56f4,0.024725156,MjU5ODc5MXxBUE18QVBQTElDQVRJT058NjE1NzE2MDM3,[app],MjU5ODc5MXxBUE18QVBQTElDQVRJT058NjE1NzE2MDM3,e1901060b5184599,5774e88bb114,[name],1.699598,639052099,true,[app],1019368b3af880ac24afc0cd43369f41,1019368b3af880ac24afc0cd43369f41,1019368b3af880ac

If I query * from the transaction table for that traceId I get:

Timestamp,App ID,App Name,Container ID,Duration,Entity GUID,Error,GUID,Host,Http.Status Code,Http Response Code,Name,Priority,Real Agent ID,Request.Method,Request.URI,Response.Headers.Content Type,Sampled,Total Time,Trace ID,Transaction Sub Type,Transaction Type
2020-03-24 13:02:50,[appId],[app],5774e88bb114c7157e0cfdab1e8150dfc58fe03c8e23ca7376fdd860795d56f4,0.024725156,MjU5ODc5MXxBUE18QVBQTElDQVRJT058NjE1NzE2MDM3,false,1019368b3af880ac,5774e88bb114,200,200,[name],1.699598,639052099,GET,[path],application/json; charset=UTF-8,true,0.024725156,1019368b3af880ac24afc0cd43369f41,Go,Web

In both cases, everything again appears identical, except in the UI the attributes show a timestamp difference of 1 ms.  

For the first case, the UI shows this:

![image](https://user-images.githubusercontent.com/16964445/77436556-01d06280-6dba-11ea-831b-e152a9ce30ab.png)

In the second case, the UI shows this:

![image](https://user-images.githubusercontent.com/16964445/77436860-5c69be80-6dba-11ea-91c3-60a32c7ce3a9.png)

I've reviewed at least 50 similar cases (2 spans, both identical), and in every instance that they are listed as "orphaned", the timestamp is off by 1 ms. Most, but not all of the non-orphaned examples have identical timestamps.  It seems to be a roughly 50/50 distribution of orphaned to non, so even though it doesn't make sense, I can't see any other pattern and the correlation seems very strong to me at this point.

 If you need any more details let me know, I can provide the attributes the UI is showing as well if needed.

**Comment by purple4reina** [comment]
@larsinmar,

Thanks for these details. I think at this point it's best that we have you open a support ticket through [support.newrelic.com](https://support.newrelic.com/). There we'll be able to share more code examples and be able to see what you're seeing in the UI. Please reference this github issue.

We'll update this issue with any conclusions we find during that process.

Looking forward to continued debugging,

Rey

**Comment by larsinmar** [comment]
I'm closing this issue as it appears to have been resolved. Thanks @purple4reina!

**Comment by purple4reina** [comment]
@larsinmar So glad to hear it! Thanks for reporting it. And you were correct, it did have to do with the timestamps! Great sleuthing!
