### ISSUE TITLE
NRgin mod outdated

### ISSUE THREAD

**Issue by filipemendespi** [newrelic/go-agent#141]
I saw that you changed the way you generate the name of the transactions. The problem is that it doesn't work for **nrgin**.

I imagine it's because they forgot to update the go.mod of the **nrgin** package in that [commit](https://github.com/newrelic/go-agent/commit/b9b65ab3d35fb31361c9869fa0788cdb60dc0f4e).

Current code:
https://github.com/newrelic/go-agent/blob/master/v3/integrations/nrgin/go.mod#L9

Could you make this correction and generate a new version?
Thank you and congratulations for the work!

**Comment by filipemendespi** [comment]
I leave as a reference this tag that induces that the code should be updated.
https://github.com/newrelic/go-agent/releases/tag/v3%2Fintegrations%2Fnrgin%2Fv2.0.0

**Comment by purple4reina** [comment]
Hey @filipemendespi,

Thanks for reporting this issue. I am having problems recreating it. What problem are you seeing when trying to run the v2.0.0 of nrgin with v3.0.0 of the newrelic agent?

R

**Comment by filipemendespi** [comment]
@purple4reina I tried all the ways to update the version of nrgin, but it doesn't. Do you have any suggestions on how to update? In my project the go-agent version is 3.4 but the nrgin version remains 1.0.

**Comment by purple4reina** [comment]
Okay, that's a problem, we'll look into it. Thanks again for reporting this!

**Comment by purple4reina** [comment]
Hey @filipemendespi,

Sorry for the delay in updating this issue. I first want to thank you for taking the time to report this issue. We've fixed it internally and plan to release the fix with our next agent release in the coming weeks. 

In the meantime, we encourage users to continue using the v1.0.0 of `nrgin`.

Thanks again and take good care,

Rey

**Comment by filipemendespi** [comment]
Thanks for the @purple4reina,

I will be waiting for the next release because the name of the transaction is exactly what we are trying to change.

**Comment by purple4reina** [comment]
@filipemendespi We just released a new version of the agent that includes these fixes to nrgin. Please let us know what you think! I am going to go ahead and close this issue, but if you have any further questions or comments, don't hesitate to ask them here.
