### ISSUE TITLE
Support jackc/pgx as a postgres driver

### ISSUE THREAD

**Issue by dankinder** [newrelic/go-agent#142]
We've been using lib/pq for quite a while, so the existing nrpq has satisfied us so far, but there are 2 issues with it.
One is that the bottom of https://github.com/lib/pq indicates that it is in maintenance mode and won't get new features. It says to use https://github.com/jackc/pgx instead.
The other is the immediate need we have now: lib/pq doesn't have any intelligent retry logic, whereas pgx does retry queries on certain safe kinds of errors. We are finding that we need this, e.g. to handle broken pipes.
Can you guys provide a package that supports jackc/pgx?

**Comment by newrelic-eheinlein** [comment]
Hi @dankinder - thank you very much for this feedback!  I am going to loop in our product manager for the Go Agent; she can take a look whether we can get this on our roadmap and how it can be prioritized.

If anyone else comes across this issue and is also looking for support for jackc/pgx, please feel free to chime in and let us know!

**Comment by etokarev** [comment]
We are also interested in supporting `jackc/pgx` by `nrpq`

**Comment by newrelic-eheinlein** [comment]
@etokarev Thanks for adding your voice! We will take note in the ticket in our backlog.

**Comment by etokarev** [comment]
@newrelic-eheinlein would it possible to provide some ETA on adding support for ` jackc/pgx`? We need to add NR instrumentation to db calls in our applications and we are currently blocked because our apps use `pgx` driver.   
Having a rough ETA will help us to decide if we want to wait for NR Agent to support it or consider with other options like switching to `pq`, writing our own instrumentation wrapper , etc

**Comment by purple4reina** [comment]
Hey @etokarev, We don't have a definitive timeline just yet on when we'll be able to get to this work. In the meantime, you can always manually create `DatastoreSegment`s using the API. Check out the detailed explanation in [the Guide](https://github.com/newrelic/go-agent/blob/master/GUIDE.md#datastore-segments).

**Comment by penguinxr2** [comment]
interested in this as well, thanks!

**Comment by jameshalsall** [comment]
This would be great 👍🏻

**Comment by wedow** [comment]
Would also really appreciate this

**Comment by jbarton123** [comment]
Interested and would really appreciate as well! Thanks!

**Comment by ghmj2417** [comment]
Interested

**Comment by ak-war** [comment]
Thank you for your valuable feedback, we welcome your ideas and it definitely helps us make crucial decisions regarding how we can best fulfill your needs. This work item is coming up on our roadmap and is being targeted for completion around the end of August.

**Comment by yulrizka** [comment]
I played around and porting the lib/pq. It seems to be working. 
https://github.com/yulrizka/nrpgx 

Let me know if you open for a PR.

**Comment by RichVanderwal** [comment]
Hi @yulrizka , we'd love to look at your PR! Even if we don't use it directly, it will certainly inform our upcoming support.
