### ISSUE TITLE
Make Transaction thread-safe

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#143]
We just had an issue where the New Relic library panicked on unsafe concurrent map access because developers were unaware of this limitation.

`Transaction` ought to be thread-safe without any bookkeeping on the client side. Concurrent calls to `StartSegment`, `StartExternalSegment`, `NoticeError`, `AddAttribute`, etc. should just work. There should be no need to use `NewGoroutine` at all.

**Comment by purple4reina** [comment]
Hello @rittneje,

Thanks for opening this issue. I am very concerned that you received a panic while trying to use the Go Agent. Could you share with us what you did in order to hit the panic? This will help us be able to better understand the problem you are describing.

As designed, the `Transaction` is thread safe. You should be able to call any of its methods from any goroutine without issue. The requirement to call `NewGoroutine` is not for thread safety but instead to help us manage segment parenting and exclusive time.

I look forward to your response,
Rey

**Comment by rittneje** [comment]
@purple4reina The panic came from the AWS SDK integration attempting to add attributes to the span. We were making multiple SDK calls in parallel within the same transaction. We are using v3.4.0 of the agent, and v1.0.0 of the integration.

> | 2020-05-08 16:36:58.055 | fatal error: concurrent map writes                                                                                                                                                           |
| 2020-05-08 16:36:58.059 | goroutine 75 [running]:                                                                                                                                                                      |
| 2020-05-08 16:36:58.059 | runtime.throw(0xbb5669, 0x15)                                                                                                                                                                |
| 2020-05-08 16:36:58.059 | /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc000667868 sp=0xc000667838 pc=0x42dfc2                                                                                                     |
| 2020-05-08 16:36:58.059 | runtime.mapassign_faststr(0xaf0440, 0xc000287ef0, 0xbaf0af, 0xd, 0x40a223)                                                                                                                   |
| 2020-05-08 16:36:58.059 | /usr/local/go/src/runtime/map_faststr.go:291 +0x3fe fp=0xc0006678d0 sp=0xc000667868 pc=0x412fee                                                                                              |
| 2020-05-08 16:36:58.059 | vendor/github.com/newrelic/go-agent/v3/newrelic.(*spanAttributeMap).add(...)                                                                                                        |
| 2020-05-08 16:36:58.059 | /app/src/vendor/github.com/newrelic/go-agent/v3/newrelic/tracing.go:183                                                                                                             |
| 2020-05-08 16:36:58.059 | vendor/github.com/newrelic/go-agent/v3/newrelic.(*spanAttributeMap).addString(...)                                                                                                  |
| 2020-05-08 16:36:58.059 | /app/src/vendor/github.com/newrelic/go-agent/v3/newrelic/tracing.go:171                                                                                                             |
| 2020-05-08 16:36:58.059 | vendor/github.com/newrelic/go-agent/v3/newrelic.(*tracingThread).AddAgentSpanAttribute(...)                                                                                         |
| 2020-05-08 16:36:58.059 | /app/src/vendor/github.com/newrelic/go-agent/v3/newrelic/tracing.go:251                                                                                                             |
| 2020-05-08 16:36:58.059 | vendor/github.com/newrelic/go-agent/v3/newrelic.(*thread).AddAgentSpanAttribute(0xc000472180, 0xbaf0af, 0xd, 0xc0005d0a20, 0x24)                                                    |
| 2020-05-08 16:36:58.059 | /app/src/vendor/github.com/newrelic/go-agent/v3/newrelic/internal_txn.go:1160 +0xc8 fp=0xc000667928 sp=0xc0006678d0 pc=0x8d8e68                                                     |
| 2020-05-08 16:36:58.059 | vendor/github.com/newrelic/go-agent/v3/internal.AddAgentSpanAttribute(...)                                                                                                          |
| 2020-05-08 16:36:58.059 | /app/src/vendor/github.com/newrelic/go-agent/v3/internal/hidden_methods.go:36                                                                                                       |
| 2020-05-08 16:36:58.059 | vendor/github.com/newrelic/go-agent/v3/internal/integrationsupport.AddAgentSpanAttribute(0xc0004700c0, 0xbaf0af, 0xd, 0xc0005d0a20, 0x24)                                           |
| 2020-05-08 16:36:58.115 | /app/src/vendor/github.com/newrelic/go-agent/v3/internal/integrationsupport/integrationsupport.go:25 +0x99 fp=0xc000667968 sp=0xc000667928 pc=0x9b0a49                              |
| 2020-05-08 16:36:58.115 | vendor/github.com/newrelic/go-agent/v3/internal/awssupport.EndSegment(0xda7160, 0xc0007d6480, 0xc000288870)                                                                         |
| 2020-05-08 16:36:58.115 | /app/src/vendor/github.com/newrelic/go-agent/v3/internal/awssupport/awssupport.go:98 +0x122 fp=0xc0006679c8 sp=0xc000667968 pc=0x9b1552                                             |
| 2020-05-08 16:36:58.115 | vendor/github.com/newrelic/go-agent/v3/integrations/nrawssdk-v1.endSegment(0xc0000ee000)                                                                                            |
| 2020-05-08 16:36:58.115 | /app/src/vendor/github.com/newrelic/go-agent/v3/integrations/nrawssdk-v1/nrawssdk.go:25 +0x5a fp=0xc0006679f0 sp=0xc0006679c8 pc=0x9b19ea                                           |
| 2020-05-08 16:36:58.115 | vendor/github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc0000ee208, 0xc0000ee000)                                                                                         |
| 2020-05-08 16:36:58.115 | /app/src/vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go:267 +0x98 fp=0xc000667a88 sp=0xc0006679f0 pc=0x7fa678                                                             |
| 2020-05-08 16:36:58.115 | vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0xc0000ee000, 0x0, 0x0)                                                                                         |
| 2020-05-08 16:36:58.115 | /app/src/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:578 +0xba fp=0xc000667b50 sp=0xc000667a88 pc=0x7fdaea                                                              |
| 2020-05-08 16:36:58.115 | vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc0000ee000, 0x0, 0x0)                                                                                                |
| 2020-05-08 16:36:58.115 | /app/src/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:531 +0x13e fp=0xc000667be8 sp=0xc000667b50 pc=0x7fd39e                                                             |
| 2020-05-08 16:36:58.115 | vendor/github.com/aws/aws-sdk-go/service/sqs.(*SQS).SendMessageWithContext(0xc000096610, 0xda7160, 0xc0001b64e0, 0xc000576180, 0x0, 0x0, 0x0, 0xd2, 0xc0000ba380, 0x0)              |
| 2020-05-08 16:36:58.115 | /app/src/vendor/github.com/aws/aws-sdk-go/service/sqs/api.go:1604 +0xae fp=0xc000667c28 sp=0xc000667be8 pc=0x95ca4e

**Comment by purple4reina** [comment]
@rittneje Thanks a ton for these details. This does in fact seem like a bug in the agent. I will do more investigating and get back to you.

**Comment by purple4reina** [comment]
@rittneje I was able to successfully reproduce the panic you've shared above. We plan to get a fix out for this bug in our next release. We really appreciate you sharing this with us! Please let us know if there's anything else we can do to improve your experience with the Go Agent.

**Comment by purple4reina** [comment]
@rittneje We just released v3.5.0 of the agent that includes this fix. Let us know if it works out for you!

**Comment by purple4reina** [comment]
I'm going to go ahead and close this issue, but if for some reason the release does not work out or you have any further concerns, please feel free to respond to it. We'll get alerted to your response and will be able to respond.
