### ISSUE TITLE
Treat segments more like nested transactions

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#144]
This will be better suited for v4 of this library, but it would be preferable that both `Transaction` and `Segment` have a `StartSegment(string) *Segment` method. Ending a transaction or segment implicitly ends all segments stacked on top of it. Starting a segment on a transaction or segment that has already ended is effectively a no-op.  Starting multiple segments in the same "scope" means they all happened in parallel.

For example:
```go
tx := app.StartTransaction("my tx")
defer tx.End()

// There is one segment under "my tx".
seg1 := tx.StartSegment("my seg")
defer seg1.End()

wg := new(sync.WaitGroup)
for _, task := range tasks {
    wg.Add(1)
    go func(task Task) {
        defer wg.Done()

        // Each task is represented as a parallel segment under "my seg".
        seg2 := seg1.StartSegment(task.Name)
        defer seg2.End()

        // task.Do might in turn make more nested segments inside the task's segment.
        if err := task.Do(seg2); err != nil {
            seg2.NoticeError(err)
        }
    }(task)
}
wg.Wait()
```

As you can see, a few other methods would also have to be added to `Segment`, such as `NoticeError`. Really, I think this API would benefit significantly from not drawing a huge distinction between a transaction and a segment, given that a segment is effectively just a nested transaction. This will also give us much more flexibility in what we see in the distributed trace.

**Comment by newrelic-eheinlein** [comment]
Hi @rittneje, thank you for this valuable feedback!  We brought this to the attention of our product manager. We do have the intention to rework how we handle nested segments in transactions in the future, so this is great feedback to get. At this point it doesn't look like we will necessarily take this specific approach - however, if you are willing, we would love to be able to contact you to get your input on this kind of change when we do make it. If you would be willing to do that, let us know and we'll plan to send you a message when we get to this specific work.

We'd also love to hear from anyone else who is running into issues and has opinions about changes like that.

**Comment by rittneje** [comment]
Yes, I would like to be involved. Thanks!
