### ISSUE TITLE
Adding support for go-micro package v2

### ISSUE THREAD

**Issue by XuesongHu** [newrelic/go-agent#145]
Currently, newrelic go-agent has support for go-micro. However the support is only for v1 and go-micro has already well on its way to v2. Please add support for v2 on go-agent.
```
import "github.com/micro/go-micro/v2"
```

**Comment by newrelic-eheinlein** [comment]
Hi @XuesongHu - thank you very much for this feedback! I have looped in our product manager for the Go Agent; she is taking a look at whether we can get this on our roadmap and how it can be prioritized. We do intend to get to this work when we can, but we don't currently have a specific target release in mind.

If anyone else comes across this issue and is also looking for support for v2 of go-micro, please feel free to chime in and let us know!

**Comment by jodeev** [comment]
I've made sure to put this in our backlog, we would definitely like to know whether others also need this, so please add a comment if you are also interested.  This will help us prioritize work.

**Comment by divyanshgaba** [comment]
@jodeev +1. Interested in this feature as well.
