### ISSUE TITLE
v3.4.0 fails with "does not contain package github.com/newrelic/go-agent/v3/internal/sqlparse" error

### ISSUE THREAD

**Issue by dysrama** [newrelic/go-agent#146]
After upgrading to v3.4.0 build on my project fails with the following error:

`cannot load github.com/newrelic/go-agent/v3/internal/sqlparse: module github.com/newrelic/go-agent/v3@latest found (v3.4.0), but does not contain package github.com/newrelic/go-agent/v3/internal/sqlparse`

I've had to downgrade to v3.3.0

**Comment by purple4reina** [comment]
Hi @dysrama, thanks for opening this issue. I assume you were able to get your issue solved? If so, would you mind sharing your solution here so others can benefit as well? Thanks again, Rey.

**Comment by Platycat** [comment]
I didn't as much solve it as realize it was only a problem on my local setup for a specific service, since I tried updating another service and didn't have issues there.

**Comment by dysrama** [comment]
I didn't as much solve it as realize it was only a problem on my local setup for a specific service, since I tried updating another service and didn't have issues there.
