### ISSUE TITLE
Integration with gRPC Server

### ISSUE THREAD

**Issue by matheus-meneses** [newrelic/go-agent#147]
Hi all, Is newrelic agent enable to work with Grpc Server?

**Comment by purple4reina** [comment]
Hey @matheus-meneses! It sure is! Check out the godocs for more details: https://godoc.org/github.com/newrelic/go-agent/v3/integrations/nrgrpc. Let us know if you have any questions about it.

**Comment by matheus-meneses** [comment]
Thanks a lot!
