### ISSUE TITLE
nrRedis with ClusterMode Opts

### ISSUE THREAD

**Issue by matheus-meneses** [newrelic/go-agent#149]
Hi all, i've been integrating go-agent and redis in cluster mode, but in cluster mode opts must be passed as nil to redisHook, something like that: 

`
 func Example_clusterClient() {
	client := redis.NewClusterClient(&redis.ClusterOptions{
		Addrs: []string{":7000", ":7001", ":7002", ":7003", ":7004", ":7005"},
	})

	txn := getTransaction()
	ctx := newrelic.NewContext(context.Background(), txn)
	pong, err := client.WithContext(ctx).Ping().Result()
	fmt.Println(pong, err)
}
`

Doing that, redis info does not appear in apm dashboard. Is there a roadmap to support RedisClusterMode Opts?

**Comment by newrelic-eheinlein** [comment]
Hi @matheus-meneses ! Thank you for posting this information. I will be investigating a little more to understand what all would be needed  to support this, and then I will bring the request to our Product Manager to determine if we can put it on our roadmap and how to prioritize it. I will let you know if we have any additional questions.

If anyone else is also interested in support for RedisClusterMode Opts, please feel free to chime in on this issue!

**Comment by purple4reina** [comment]
@matheus-meneses,

Thanks again for opening this detailed issue! I have some good news for you. Our existing nrredis instrumentation will work just fine using a Cluster Client.

```go
client := redis.NewClusterClient(&redis.ClusterOptions{
    Addrs: []string{":7000", ":7001", ":7002", ":7003", ":7004", ":7005"},
})
client.AddHook(nrredis.NewHook(nil))

txn := getTransaction()
ctx := newrelic.NewContext(context.Background(), txn)
pong, err := client.WithContext(ctx).Ping().Result()
fmt.Println(pong, err)
```

Notice that you will need to use `nil` for the opts when creating the hook. These options are used in a `redis.Client` to add context on host/port to your metrics. Unfortunately this means that when using the Cluster Client, we will not be able to gather these details. You will however still be able to see metrics for all your redis calls.

Hope this helps!

Rey
