### ISSUE TITLE
issues with v3/integrations/nrpq

### ISSUE THREAD

**Issue by daesu** [newrelic/go-agent#151]
Hey all I just started using the go-agent for new relic with the pq integration `https://github.com/newrelic/go-agent/tree/master/v3/integrations/nrpq` for a graphql API. 

It seems to work mostly fine but I'm getting numerous instances of errors regarding segments in the logs. For example; 
```json
ERRO[0007] unable to end datastore segment               collection=pages component=newrelic operation=select product=Postgres reason="improper segment use: segments must be ended in \"last started first ended\" order: use https://godoc.org/github.com/newrelic/go-agent/newrelic#Transaction.NewGoroutine to use the transaction in multiple goroutines"
```

The link in the error is not valid but looking at the docs for `NewGoRoutine` it seems something I should be adding if I am creating my own segments. At this point the only integration I have done is to use the nrpq driver and add the transaction in the middleware. 

I'm not sure if this is an issue with my setup or if I should be doing more to integrate nrpq than I have done. Any help would be much appreciated. 

My setup looks like the following; 

init New Relic
```go
	app, err := newrelic.NewApplication(
		newrelic.ConfigAppName(NewRelicAppName),
		newrelic.ConfigLicense(newRelicLicense),
		nrlogrus.ConfigLogger(log.GetLogger()),
		func(cfg *newrelic.Config) {
			cfg.CustomInsightsEvents.Enabled = false
		},
	)
	NewRelicApp = app
```

Transaction is called from middleware like so; 
```go
return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			txn := config.NewRelicApp.StartTransaction(config.NewRelicAppName)
			w = txn.SetWebResponse(w)
			txn.SetWebRequestHTTP(r)

			defer txn.End()
			r = newrelic.RequestWithTransactionContext(r, txn)
			next.ServeHTTP(w, r)
		})
	}
```

And I'm using the nrpq driver as so; 
```go
sqldb, err := sql.Open("nrpostgres", databaseURL)
```

SQL queries are made using sqlx. github.com/jmoiron/sqlx

env go1.14, linux, postgres.

**Comment by purple4reina** [comment]
@daesu,

Thanks a ton for opening this issue. I'd love to help you get to the bottom of these errors you're seeing.

First off, thanks for pointing out the broken link in the error message. We'll go ahead and fix that!

As for your app, before offering a recommendation, I'd like to try to understand what you're doing a bit better. In your web transactions, are you creating any goroutines? If so, are the postgres calls happening inside these goroutines? If that's the case, then we'll definitely want to use the `txn.NewGoroutine` api.

Take care,
Rey

**Comment by Ak-x** [comment]
Closing this ticket due to inactivity - please reopen if this issue still persists.
