### ISSUE TITLE
Data race in RoundTripper

### ISSUE THREAD

**Issue by blixt** [newrelic/go-agent#153]
These lines run for every individual round trip:

https://github.com/newrelic/go-agent/blob/892720022a6ff795111b96919ab44b60c9d12ed2/instrumentation.go#L85-L87

This means a data race can be triggered for two parallel requests using this RoundTripper. I don't think this is very harmful in this case since they always write the same value so even though it's indeterministic which write will be read, the value will be the same.

This still triggers Go's data race warnings so it's quite noisy and I would recommend moving these lines to the outer scope to fix the issue.

**Comment by purple4reina** [comment]
@blixt Thanks so much for reporting this. That is indeed a problem. We'll get it fixed as soon as we can.

Take good care,
Rey

**Comment by purple4reina** [comment]
Hey @blixt . We will be including a fix for this in our next release. Thanks again for reporting it.

**Comment by newrelic-eheinlein** [comment]
I @blixt ! We have released version 3.6.0 today, and it includes a fix for this issue. Thanks again for reporting it! I'll close the issue now but let us know if you see any additional problems.
