### ISSUE TITLE
v3 agent: Integration package for Kafka

### ISSUE THREAD

**Issue by jodeev** [newrelic/go-agent#160]
Please add your comments: Who needs support for Kafka? Which client library do you want to see support for?

Popular options include:

- [sarama](https://github.com/Shopify/sarama)

- [confluent-kafka-go
](https://github.com/confluentinc/confluent-kafka-go)

- [kafka-go](https://github.com/segmentio/kafka-go)

Aha! Link: https://newrelic.aha.io/features/GO-75 #

**Comment by smoyer64** [comment]
I'd love to have a wrapper for the `confluent-kafka-go` package - I see this is listed as help-wanted but do you have a bit more guidance on what you'd expect (and where to start)?

**Comment by RichVanderwal** [comment]
Hi @smoyer64 ! Instrumenting libraries is complicated and rewarding.[ Here's a doc from this repo's wiki ](https://github.com/newrelic/go-agent/wiki/Writing-a-New-Integration-Package)about what we normally do.

Also, I noticed an [outstanding issue](https://github.com/newrelic/go-agent/issues/240) regarding supporting MessageConsumer segments alongside our support for MessageProducer segements. 

We'll have to spend some time getting up to speed about what's really necessary to get Kafka instrumentation going. I'll ping our Product Manager to make sure they know that we have at least three people involved in this GitHub issue.

**Comment by wedneyyuri** [comment]
confluent-kafka-go support would be nice! Currently we are creating a new transaction for every record received from the consumer side. 

Even if you don't want to build the integration can you point us to a guide describing the pattern to build pub/sub instrumentations?

**Comment by Ak-x** [comment]
We are tracking this elsewhere under https://github.com/newrelic/go-agent/issues/563
