### ISSUE TITLE
v3 agent: Support jackc/pgx as a postgres driver

### ISSUE THREAD

**Issue by jodeev** [newrelic/go-agent#179]
Our existing [nrpq](https://github.com/newrelic/go-agent/tree/master/v3/integrations/nrpq) integration package needs an update. we need to add support for the jackc/pgx driver.

The currently supported driver is [https://github.com/lib/pq](https://github.com/lib/pq), which is now in maintenance mode. That repo says to use [https://github.com/jackc/pgx](https://github.com/jackc/pgx) instead.

More importantly, lib/pq doesn't have any intelligent retry logic, whereas pgx does retry queries on certain safe kinds of errors. Users need this to do things such as handle broken pipes.

**Acceptance criteria**

- the go agent v3 integration package for postgres, [https://github.com/newrelic/go-agent/tree/master/v3/integrations/nrpq](https://github.com/newrelic/go-agent/tree/master/v3/integrations/nrpq), supports the jackc/pgx driver
- unit tested

Original issue: [https://github.com/newrelic/go-agent/issues/142](https://github.com/newrelic/go-agent/issues/142)

**Comment by jodeev** [comment]
Comment added by Jon Connelly in Aha! - [View](https://newrelic.aha.io/comments/6875335879733463446)

[@Jodee Varney](https://newrelic.aha.io/users/6592195190187755325) does this relate to updating the driver?

My customer has a support issue that suggests it could be solved by updating the Go driver and I want to confirm this is the enhancement request that would relate to the issue. Thank you for any insights.

Support case: [https://newrelic.zendesk.com/agent/tickets/413756](https://newrelic.zendesk.com/agent/tickets/413756)

"I’m pretty out of ideas on this one. Unfortunately, we couldn’t update to the latest version of the driver because it requires a newer version of Go than the one the integrations are built with, so it’s still possible that could help, but it’s not really doable right now. I’m unable to reproduce it myself, and don’t really have any more information I can think of that might help"

**Comment by marcesher** [comment]
Huge +100 for this one!

**Comment by RichVanderwal** [comment]
This has been moved into the roadmap for completion in August.
