### ISSUE TITLE
Best way to identify an http transaction error

### ISSUE THREAD

**Issue by danbrakeley** [newrelic/go-agent#20]
Our Go http service is using New Relic to log transactions for each request, and I'm curious what controls the "Message" field in the error log? Currently it appears to be filled in with the text version of the http status code (ie Internal Server Error for any 500), for example:

![image](https://cloud.githubusercontent.com/assets/6772870/19665015/ff46af54-9a10-11e6-9f02-187ab12a97c7.png)

We have custom errors in our code, and I would like to set that Message field to the text of the actual error. Is that possible? I tried using SetName, but that change the URL, not the Message.

Note that if I start my own Transaction and call NoticeError, then the error text appears as the Message field. This is the behavior I want to mimic for http transactions.

**Comment by willnewrelic** [comment]
Hi Dan

I presume you are using `WrapHandle` and/or `WrapHandleFunc` and would like to notice an error in one of your handlers?  Use type assertion on the `http.ResponseWriter`:

```go
func noticeError(w http.ResponseWriter, r *http.Request) {
	if txn, ok := w.(newrelic.Transaction); ok {
		txn.NoticeError(errors.New("my error message"))
	}
}
```

**Comment by danbrakeley** [comment]
So when I do that, I end up with 2 errors in new relic, not 1.

**Comment by willnewrelic** [comment]
Disabling the normal http response code error instrumentation (and using `NoticeError`) will be easier than modifying the agent.  I recommend adding the following configuration:

```go
cfg.ErrorCollector.IgnoreStatusCodes = []int{500, 501} // and any other codes
```

I understand the friction here:  It would be nice to easily add some "why" context to the automatically captured response code errors.  We will contemplate this.

**Comment by danbrakeley** [comment]
Excellent, that was what I was trying to get at. I was about to ask if there was a way to disable the default status code error. Thanks, I'll try that now!

**Comment by danbrakeley** [comment]
@willnewrelic Hmm, on second thought, this sucks. If I want to never have those errors fire, I need to list all 400 and 500 status codes?

Alternatively, I can add my error to the current transaction via AddAttribute, and in the new Error Analytics view, I can click on that custom attribute to get a listing by count of each error string. That seems like the best solution so far.

**Comment by willnewrelic** [comment]
Understood.  A setting to disable status code errors entirely would be great here.  We will discuss this.

Happy to hear the attribute/error-analytics approach is working!

**Comment by lpetre** [comment]
Are you suggesting a way to disable the status code errors per-transaction or globally?

**Comment by willnewrelic** [comment]
@lpetre Considering anything and everything!  A transaction method for per-transaction disabling would be more powerful, but a global config setting in the Config would be simpler for customers that want to always have it disabled.
