### ISSUE TITLE
v3/integrations/nrpq: SQL query not displayed in datastore segement

### ISSUE THREAD

**Issue by Dilip-Nandakumar** [newrelic/go-agent#208]
## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

SQL query not displayed in slow query data samples section for datastore segments created using nrpq integration package

Rather a text of the following format is displayed 

`
‘sqlOperation’ on ‘tableName’ using ‘DatabaseName’
` 

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

Create a datastore segment using nrpq using the [example](https://github.com/newrelic/go-agent/blob/master/v3/integrations/nrpq/example/main.go)

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

SQL query to be displayed

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

| Package  | Version |
| ------------- | ------------- |
| github.com/newrelic/go-agent/v3  | v3.8.1 |
| github.com/newrelic/go-agent/v3/integrations/nrpq  | v1.1.0  |
| github.com/lib/pq  | v1.8.0  |

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

1. Security policy allows display of parameterized query.

2. In [ParseQuery](https://github.com/newrelic/go-agent/blob/master/v3/newrelic/sqlparse/sqlparse.go#L57
) we are not setting the `ParameterizedQuery` & `QueryParameters` field of the start datastore segment

**Comment by newrelic-eheinlein** [comment]
Hi @Dilip-Nandakumar ! Thank you for reporting this.  Our Product Manager is aware of the issue and will prioritize the investigation.

**Comment by fabianedl** [comment]
Hi, I found the same problem in v3/integrations/nrmysql

**Comment by vivekmittal** [comment]
Same issue with nrpgx. Any updates here?

**Comment by Ak-x** [comment]
Hey @vivekmittal , @fabianedl , @Dilip-Nandakumar ; we have created an FR to track this on our public Jira: https://issues.newrelic.com/browse/NEWRELIC-4158.

If you connect with our support team you can be added as a watcher; otherwise this will be public in the near future for you all to monitor its progress.
