### ISSUE TITLE
Due to name and package name clashing, go-agent is unusable with goimports

### ISSUE THREAD

**Issue by deftworker** [newrelic/go-agent#21]
If you have installed the goimports plugin with gosublime for sublime text, the plugin automatically manages import statements. Since the go-agent name is different from the newrelic package name called inside main or init, the goimports plugin immediately wipes the import statement from the file on save.  See discussion with the go team: https://github.com/golang/go/issues/17576

Per bradfitz:
goimports will respect any of these options:

package newrelic in github.com/newrelic/go-agent/newrelic
package agent in github.com/newrelic/go-agent
package goagent in github.com/newrelic/go-agent (after #17546 at least)

**Comment by willnewrelic** [comment]
Hi deftworker

The solution is to use named imports.

```go
import (
	newrelic "github.com/newrelic/go-agent"
)
```
