### ISSUE TITLE
Only a span for sqlx.GetContext is missing

### ISSUE THREAD

**Issue by soichisumi** [newrelic/go-agent#217]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I've run the example but a span for sqlx.GetContext seems not shown.

## Steps to Reproduce

example code:
https://github.com/soichisumi/go-snippets/blob/master/lib/newrelic/newrelic.go

## Expected Behavior

3 spans are shown after `MySQL person select` span
![image](https://user-images.githubusercontent.com/30210641/90328648-174c6000-dfd9-11ea-9e49-37506d0e94ac.png)

## Your Environment

* Go 1.14.4
* newrelic/go-avent v3.8.1

## Additional context

* my code is almost same with a sample
  * https://github.com/newrelic/go-agent/blob/master/v3/integrations/nrpq/example/sqlx/main.go

**Comment by newrelic-eheinlein** [comment]
Hi @soichisumi ! Thank you for reporting this, and for providing the steps to reproduce it.  We will take a look and get back to you!
