### ISSUE TITLE
Add example go.mod files

### ISSUE THREAD

**Issue by newrelic-eheinlein** [newrelic/go-agent#219]
Our [v3 integration packages](https://github.com/newrelic/go-agent/tree/master/v3/integrations) all have example apps, but those sample apps don't currently have `go.mod` files. We should ensure that each example has a go.mod file that follows standard best practices.

**Comment by RichVanderwal** [comment]
All the integrations have go.mod files except for **nrb3**

**Comment by RichVanderwal** [comment]
We can make these go.mod files, but that means any godocs information in the sample applications won't show up on pkg.go.dev.

**Comment by rvanderwal-newrelic** [comment]
...unless we make a separate tag for each example and keep it updated.

**Comment by RichVanderwal** [comment]
Let's not do this, so we don't have the overhead of dealing with all those tags.
