### ISSUE TITLE
NewRoundTripper always uses a nil transaction (in the v3 API)

### ISSUE THREAD

**Issue by zeffron** [newrelic/go-agent#234]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

`NewRoundTripper()` is documented as retrieving the transaction from the request's context, but it does no such thing. This means that is fails to properly record the request in the transaction, and leads to incomplete data in APM.

Instead, it [always uses nil for the transaction when starting the external segment](https://github.com/newrelic/go-agent/blob/master/v3/newrelic/instrumentation.go#L89).

This means that, contrary to the documention, for correct usage, all calls must still be wrapped in manual `StartExternalSegment()` and `segment.End()`, defeating the purpose of using a custom `Transport` in the first place.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

Use the `NewRoundTripper()` function to set a custom RoundTripper on the http client.
```go
request, err := http.NewRequest(http.MethodPut, url, bytes.NewBuffer(data))
client := &http.Client{}
client.Transport = newrelic.NewRoundTripper(client.Transport)
transaction := newrelic.FromContext(ctx)
request = newrelic.RequestWithTransactionContext(request, transaction)

response, err := client.Do(request)
```

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

Using a `NewRoundTripper()` for the transport on an http client does not require explicit calls to `StartExternalSegment()` to record the request in the transaction.

## Additional context

Can be fixed by replacing the `nil` on the above referenced line with `FromContext(request.Context())`

[TIP]:  # ( Add any other context about the problem here. )

**Comment by rittneje** [comment]
`NewRoundTripper` calls `StartExternalSegment(nil, request)` as you mentioned.
https://github.com/newrelic/go-agent/blob/d1121710a4067a482f4baea39e17052bc89d03a7/v3/newrelic/instrumentation.go#L82-L98

However, `StartExternalSegment` will pull the transaction from the request context if the first parameter is `nil`.
https://github.com/newrelic/go-agent/blob/d1121710a4067a482f4baea39e17052bc89d03a7/v3/newrelic/segments.go#L282-L300

Thus it appears that the current implementation already works as intended.

**Comment by zeffron** [comment]
Interesting. There's some sort of bug somewhere, though, because when I manually added calls to `StartExternalSegment()` (or made the change I suggested locally) I had data for all of my calls, but when I didn't, only one (or sometimes two) of the calls would show up in APM metrics.

I agree, from the code you linked, it looks like that's already handled.

Could the issue be that something is going wrong with copying the context in `cloneRequest` and it is losing the transaction?

**Comment by zeffron** [comment]
> Could the issue be that something is going wrong with copying the context in `cloneRequest` and it is losing the transaction?

Looks like that should work just fine: https://play.golang.org/p/Nq3Vp2QqzXG

**Comment by rittneje** [comment]
Can you expand upon what you are doing? Is this a long-lived application?

**Comment by zeffron** [comment]
It's a web API server that processes configuration change requests from clients and pushes the changed configurations to the appliances. In testing, we had three appliances connected, and we were seeing metrics in APM for only one or two of the calls to the appliances for each client change request when using the RoundTripper to auto-instrument. One transaction per client request results in one external request to each appliance. We execute these in parallel, but we use NewGoRoutine to create a new sub-transaction for each of those requests.

NewRoundTripper is used to configure a Transport for http clients which are made per-request (no client reuse)

Using manual calls to StartExternalSegment passing in the transaction instead of using the RoundTripper, or modifying the RoundTripper as described in the OP resulted in all three calls to the appliances showing up in APM for each transaction.

**Comment by zeffron** [comment]
When I have a minute, I'll modify NewRoundTripper back to the way it is in master and try again, just to confirm we didn't accidentally make another change at the same time.

**Comment by zeffron** [comment]
With the code reverted, I'm now still seeing all of the transactions showing up. Not sure what the issue was before (maybe an issue with the new visualization view and not with APM's collection).
