### ISSUE TITLE
How to use new externally-managed named pipe feature in lambdas?

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#235]
The 3.9.0 release notes just say this:
> When sending Serverless telemetry using the nrlambda integration, support an externally-managed named pipe.

However, they don't explain any further. How do I use an externally-managed named pipe? Why would I want to? Do I need to use a special lambda layer? It would be helpful to add instructions to these release notes.

**Comment by RichVanderwal** [comment]
Hi @rittneje , you're right, this could have been documented better! 

Normally our serverless telemetry integration simply writes to STDOUT, but this new tiny feature allows the lambda to write to a named pipe if it exists. I'll look at our schedule and see if we can get less confusing statement about this functionality in front of our customers. 

Thanks for the heads-up!

**Comment by jodeev** [comment]
This is related to our new announcement: https://blog.newrelic.com/product-news/free-observability-plan-aws-marketplace/ 
and now we need to clean up our Release notes to indicate how this feature is used, and add to our docs.

**Comment by Ak-x** [comment]
@rittneje We will be updating our Release notes on 3.9.0, and in the meantime feel free to check this documentation on some additional information regarding the Lambda pipeline: 

- [Legacy Manual Instrumentation](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy/)
- [Enable Monitoring for AWS Lambda](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/)
- [Layer Installation Instructions](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own/#quickstarts)
- [Sample Go Application](https://github.com/newrelic/newrelic-lambda-extension/tree/main/examples/sam/go)

**Comment by Ak-x** [comment]
Closing this issue as the [3.9.0 release notes have now been updated](https://docs.newrelic.com/docs/release-notes/agent-release-notes/go-release-notes/go-agent-390/) with additional support and instructions listed above.
