### ISSUE TITLE
AWS IMDS V2 Support

### ISSUE THREAD

**Issue by ericlarssen-wf** [newrelic/go-agent#238]
## Summary
AWS has created a newer protocol to communicate with the Metadata server ([context](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html)), that enables clients to use a session based request which is more secure. With the idea of deprecating the usage of the V1 protocol, we rely on the agent to no longer use that authentication method.

## Desired Behaviour
Adopt the session based authentication with the AWS metadata server.

### Describe Alternatives
None that I can think of.

### Additional context
https://krebsonsecurity.com/2019/08/what-we-can-learn-from-the-capital-one-hack/

**Comment by RichVanderwal** [comment]
Hi @ericlarssen-wf , thanks for this request! I've reviewed the Java Agent changes to accept this token and forward it through with the next IMDS request, and now I'll bring our Product Manager in on this one to get her input on how this works with our roadmap.
