### ISSUE TITLE
Add Support to go redis v8

### ISSUE THREAD

**Issue by matheus-meneses** [newrelic/go-agent#239]
## Summary

Go Redis has released go-redis v8 https://github.com/go-redis/redis

## Desired Behaviour

Add support to go redis v8

**Comment by RichVanderwal** [comment]
Hi @matheus-meneses ! We're looking at the differences between Redis 7 and last September's Redis 8, and I'm raising this to the attention of our Product Manager to see how this fits into our roadmap.

**Comment by ilmimris** [comment]
Hi everyone, I make PR https://github.com/newrelic/go-agent/pull/251 add support go redis v8. What I've done is duplicate code nrredis-v7 and change some code to support go redis v8 such as add context to some methods.

**Comment by namco1992** [comment]
Hello we would like to see this implemented too, thanks!

**Comment by jodeev** [comment]
closed with https://github.com/newrelic/go-agent/pull/251
