### ISSUE TITLE
Add transaction types for message consumers

### ISSUE THREAD

**Issue by v3n** [newrelic/go-agent#240]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Support Message Consumer segments, similar to the Java agent.

## Desired Behaviour

- Allow instrumentation of queue/topic consumption calls, similar to how MessageProducer allows for instrumenting producer calls.
- _Nice to have:_ AWS integration automatically creates MessageConsumer segments for calls to SQS.
- _Nice to have:_ Integration for popular Go Kafka libraries.

## Additional context

We have a batch processing system that uses a Kafka queue for permanence between two services. A single API call to the root service creates one batch. We would like to use distributed tracing to understand the latency from each send onto the topic in SERVICE A to the time SERVICE B has picked up the message from the topic and inserted into into a database.

**Comment by RichVanderwal** [comment]
Hi @v3n! Thanks for your feature request -- we crave feedback like this. I've looped in our Product Manager to see what we can do as far as including it in our roadmap.

**Comment by Ak-x** [comment]
This is tracked under: https://github.com/newrelic/go-agent/issues/563
