### ISSUE TITLE
v3/integrations/go-chi/chi: instrument middlewares

### ISSUE THREAD

**Issue by wedneyyuri** [newrelic/go-agent#241]
Hi guys, would be nice to have an plug and play instrumentation middleware for go-chi/chi. It's lightweight, fast and 100% compatible with net/http.

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

It's expected to be really easy to use. Something like:

```go
package main

import (
	"net/http"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
        "github.com/newrelic/go-agent/v3/newrelic"
        "github.com/newrelic/go-agent/v3/integrations/nrchi"
)

func main() {
	app, err := newrelic.NewApplication(
		newrelic.ConfigAppName("Chi App"),
		newrelic.ConfigLicense(os.Getenv("NEW_RELIC_LICENSE_KEY")),
		newrelic.ConfigDebugLogger(os.Stdout),
	)
       if nil != err {
		fmt.Println(err)
		os.Exit(1)
	}

	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Use(nrchi.middleware)
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("welcome"))
	})
	http.ListenAndServe(":3000", r)
}
```

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Easy to use middleware.

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

This package give us the [RoutePattern](https://github.com/go-chi/chi/blob/master/context.go#L137) method, but it's only available after serving the request.

I tried to use something like this, but seems like the transactions are being duplicated. 

```go
func NewRelicMiddleware(app *newrelic.Application) func(next http.Handler) http.Handler {
	return func(h http.Handler) http.Handler {
		fn := func(w http.ResponseWriter, r *http.Request) {
			txn := app.StartTransaction(r.Method + " " + r.RequestURI)
			defer txn.End()

			w = txn.SetWebResponse(w)
			txn.SetWebRequestHTTP(r)
			r = newrelic.RequestWithTransactionContext(r, txn)

			h.ServeHTTP(w, r)

			// routePattern is only available after ServerHTTP be called.
			routePattern := chi.RouteContext(r.Context()).RoutePattern()
			txn.SetName(r.Method + " " + routePattern)
		}
		return http.HandlerFunc(fn)
	}
}
```

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

Current result:

![image](https://user-images.githubusercontent.com/7511692/96189746-77974980-0f17-11eb-9ab0-0decfa1b3aef.png)

**Comment by RichVanderwal** [comment]
Hi @wedneyyuri, thanks for your detailed description of what you'd like to see regarding chi instrumentation! This really helps us when we're thinking about what to implement next. 

I've called this to the attention of our Product Manger, and she'll let us know if and when we can get this on our roadmap.

**Comment by wedneyyuri** [comment]
Thanks Rich, can you confirm please if it's right to call txn.SetName after
the request was made?

As far I know, txn.SetName can be called many times before ending the
transaction (the last call will be the winner) so I really don't know why
my example is not working as expected.

**Comment by RichVanderwal** [comment]
Hi @wedneyyuri , sorry for the delayed response. From a quick glance, yes, you should be able to call txn.SetName before ending the transaction, and the request your code makes shouldn't cause any problems. SetName really is a bare-bones setter method it doesn't do anything that might duplicate the transaction.

I haven't run your example, but if you set up a debug logger, do the `analytic_event_data` payloads show the new transaction name or the old one? Or both? If transactions were indeed being duplicated, I assume they'd be doppelgangers in all ways but the transaction name. Do you see matched pairs of transactions in that output?

**Comment by wedneyyuri** [comment]
Thanks @RichVanderwal ! The issue was caused by a cache middleware interecepting the request.

**Comment by AFMiziara** [comment]
Hey guys, any news on that? `go-chi/chi` is really growing fast, it would be interesting to have NR plugin to plug like we have for other web frameworks.

**Comment by willie** [comment]
Does it makes sense for New Relic to maintain it, the chi community to maintain it, or would folks accept a third-party middleware as the solution? I ask because I've had to solve this problem myself, but it's not clear what the right path forward should be for others to get to use it.

**Comment by AFMiziara** [comment]
That's a good question @willie. If we follow the pattern so far (with `httprouter`, `gin`, `gorilla/mux`), than I believe New Relic would maintain it. As I understand they even have a product team for that stuff. 

Also, if you have some solution open-source for that, I would be happy to take a look. We are considering move to `chi`.
