### ISSUE TITLE
Unable to see CPU and Memory usage in new-relic Web UI after running example under go-agent/v3/examples/short-lived-process/main.go

### ISSUE THREAD

**Issue by ashutosh-valuelabs** [newrelic/go-agent#244]
I want to track CPU and Memory usage of golang (streaming application using kafka which does not terminate) which does not have any http transaction. 
## Description
I tried by running this example [https://github.com/newrelic/go-agent/blob/master/v3/examples/short-lived-process/main.go](url) 
But CPU and Memory usage graphs does not show any data under (Go runtime option) New Relic UI for this application.

## Steps to Reproduce
Under go-agent/v3/examples/short-lived-process/main.go
In main.go and add your New Relic licence key and run the program. 

## Expected Behavior
CPU and Memory usage statistics of application should be visible.

## NR Diag results
```
(12937) 2020/11/13 13:34:48.884034 {"level":"debug","msg":"rpm request","context":{"command":"preconnect","payload":[{"high_security":false}],"url":"https://collector.newrelic.com/agent_listener/invoke_raw_method?license_key=######licence key######\u0026marshal_format=json\u0026method=preconnect\u0026protocol_version=17"}}
(12937) 2020/11/13 13:34:49.767906 {"level":"debug","msg":"rpm response","context":{"command":"preconnect","response":{"return_value":{"redirect_host":"collector-010.newrelic.com"}},"url":"https://collector.newrelic.com/agent_listener/invoke_raw_method?license_key=######licence key######\u0026marshal_format=json\u0026method=preconnect\u0026protocol_version=17"}}
(12937) 2020/11/13 13:34:49.775665 {"level":"debug","msg":"error gathering utilization data","context":{"datatype":"docker","error":" is not 64 characters long"}}
```
## Environment
New Relic version :- v3.9.0
Golang Version :- go1.13.8 linux/amd64

**Comment by RichVanderwal** [comment]
Hi @ashutosh-valuelabs , thanks for bringing this to our attention!

The Go agent, when launched, sets up a 60-second ticker. Every tick, system information like CPU and memory usage is gathered and merged into the metric harvest. In the case of the "Short-Lived Process" example, the execution doesn't last 60 seconds, so the information is never gathered.

We hope this answers your questions and addresses your concerns! Feel free to experiment with that demo application, adding execution time to see the information gathered every 60 seconds, after 60 seconds has passed.

              -->Thanks,
                     -->Rich
