### ISSUE TITLE
Export the defaultConfig function

### ISSUE THREAD

**Issue by git-hulk** [newrelic/go-agent#245]
## Summary

we are using the old version `go-agent` which allows us to use `NewConfig` to create the default config, but it seems was removed since v3. Does it make sense that exported the `defaultConfig` to make compatible with the old one? another ugly way may copy the `defaultConfig`, but I don't think it's a good idea.

## Desired Behaviour

export the function `defaultConfig`

## Possible Solution

rename `defaultConfig` to `DefaultConfig`

**Comment by jodeev** [comment]
@git-hulk Can you share more about why you need this? What problem are you trying to solve?

**Comment by git-hulk** [comment]
Thanks for your reply.

We want to allow to custom some `newrelic` options with the config file and use the default value if missing, so we need a copy of the `DefaultConfig`.

**Comment by RichVanderwal** [comment]
Hi @git-hulk , the normal, "v3"-way of doing this is to use NewApplication(), and override the default configuration settings as needed. This seems to be doing exactly what you describe.

For common settings like AppName and License, there are standard setter functions. For more esoteric settings, you can override the default settings with a custom in-line function of your own.

For instance, here I'm getting a new application with default settings, then overriding the application name, license, key, logger, host display name, and transaction tracer threshold duration:

```go
	app, err := newrelic.NewApplication(
		newrelic.ConfigAppName("My Sample Application"),
		newrelic.ConfigLicense("227e8793z9d76ec0a73c2fab22a99e8eac219487"),
		newrelic.ConfigDebugLogger(os.Stdout),
		func(config *newrelic.Config) {
			config.HostDisplayName = "Zeus"
			config.TransactionTracer.Threshold.Duration = 123
		},
	)
```
All the other fields that aren't mentioned are set to the default settings, so I'm good to go. Let me know if this isn't what you need!

**Comment by git-hulk** [comment]
Thanks @RichVanderwal 

I know the way to overwrite options by `NewApplication`, but I need to overwrite options in our code. I have a workaround by copying the default config to our code and overwrite it.

I would close this issue soon.
