### ISSUE TITLE
integration with github.com/urfave/negroni

### ISSUE THREAD

**Issue by rayjlinden** [newrelic/go-agent#253]
Need help writing middleware for Negroni integration.

## Summary

We use Negroni which is a package for managing middleware.  We use that with vestigo as our router.  Neither of these appear to have existing integrations with NewRelic.  Well OK, maybe I'll just write it myself.

I got pretty far - but now have a problem.  Negroni itself wants to wrap and the ResponseWriter.  So when I attempt to release the response writer with a line like this:
```
rw = txn.SetWebResponse(rw)
```

Well... Negroni blows up.  (Specifically, something down the road expects the response writer to implement the Negroni.ResponseWriter interface.)

## Desired Behaviour

Somehow do the equivalent of ```rw = txn.SetWebResponse(rw)```
but keep the interface of Negroni.ResponseWriter()

Any ideas?

## Possible Solution

I'm stumped...

## Additional context

Doing an eval of Newrelic.  We have 35+ services all built with vestigo and Negroni.  So figuring this out is kind of key for use figuring out if NewRelic will work for us.

**Comment by Ak-x** [comment]
Hello @rayjlinden, checking in to see if this is still a current issue for you and your team.

**Comment by ak-war** [comment]
Hi @rayjlinden, please let us know if this is still an issue for you. We will close this item in 15 days in case we do not hear back.
