### ISSUE TITLE
Don't use internal methods in integrations

### ISSUE THREAD

**Issue by rayjlinden** [newrelic/go-agent#256]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

You have a nice set of integrations.  However, it is certainly not complete and given the nature of Go and Open Source will never be complete.  Sometimes we developers will need to write our own integrations or customize the ones you have.

Which is why it is rather troublesome to see your integrations use internal methods.  In my humble opinion, you should not use internal methods in those integrations...

I get the desire to hide "unpublished" funcs you may not want to define as public and have to support.  You need to be able to evolve the app.  However, by locking them behind internal it really reduces how one can integrate custom middleware and packages.

For example, we have a need for a custom "recovery" middleware in our application.  Currently I have a choice - use your "reporting" of panics and miss information because the panic is replaced with a new one, or do not use your panic handling, but then I can not report the panic in the same way (no access to the same stack trace mechanism, for example.)
(Maybe there is a way around this???)

Anyway, just a thought...

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by jodeev** [comment]
Yes, in retrospect we would not take this approach again.

Going forward. We love OpenTelemetry!

We plan to introduce a Shim that will allow users to leave their Go Agent instrumentation in place, add any available OpenTelemetry integration packages for Golang, and use the full Go OpenTelemetry SDK including first class support for dimensional metrics (when that is available from the OTel community).
