### ISSUE TITLE
Add zap sink for newrelic logs

### ISSUE THREAD

**Issue by stuart-warren** [newrelic/go-agent#258]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )
Provide support for sending Uber/zap logs to newrelic logs

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )
Should be able to configure zap to send logs to newrelic logs api

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )
Implement zap sink interface https://godoc.org/go.uber.org/zap#Sink

Eg https://github.com/jeffzhangme/zapx

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )
Using a PAAS and unable to add separate log shipper

**Comment by Ak-x** [comment]
Thanks for your inquiry @stuart-warren; this issue is currently being handled in https://github.com/newrelic/go-agent/issues/257.
