### ISSUE TITLE
Support for stats-d lib integrations

### ISSUE THREAD

**Issue by rayjlinden** [newrelic/go-agent#259]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

We use the library github.com/cactus/go-statsd-client/statsd in a LOT of places.  Currently that all goes to a an influx db and we have a bunch of graphana charts looking at the data.

I'm interested in checking out new relic as a potential replacement.  While integrations with many packages exist.  I do not see one for this package or any other stated library for that matter.

## Desired Behaviour

Maybe I'm missing something?  Is there something you can point me to?

In lie of that - I don't mind writing my own wrapper.  However, it is unclear to me how to map the stats APIs to the "CustomMetric" API the new relic go-agent provides.  The docs I've seen so far are a bit terse...  (Indeed, I'm finding more articles suggesting I should check DataDog instead when it comes to metrics...)

The core interface (that is used all over our code base) is:
```
type StatSender interface {
	Inc(string, int64, float32) error
	Dec(string, int64, float32) error
	Gauge(string, int64, float32) error
	GaugeDelta(string, int64, float32) error
	Timing(string, int64, float32) error
	TimingDuration(string, time.Duration, float32) error
	Set(string, string, float32) error
	SetInt(string, int64, float32) error
	Raw(string, string, float32) error
}
```

I guess I'm looking for guidance or suggestions on how to go about mapping that interface to to new relic API.

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by Ak-x** [comment]
Thank you for your inquiry @rayjlinden. Our team wanted to check in and see if this issue relating to mapping the interface to the new relic API is still an issue for you.

**Comment by ak-war** [comment]
Hi @rayjlinden, please let us know if this is still an issue for you. We will close this item in 15 days if we do not hear from you.
