### ISSUE TITLE
"nil dereference" when using DAX

### ISSUE THREAD

**Issue by odannyc** [newrelic/go-agent#287]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When using DAX to query a dynamodb table and instrumenting the request with newrelic, I get a nil reference panic on this line:
https://github.com/newrelic/go-agent/blob/master/_integrations/nrawssdk/v1/nrawssdk.go#L28

```golang
internal.EndSegment(ctx, req.HTTPResponse.Header)
```

I stepped/debugged through a request and it looks like `HTTPResponse` is nil for DAX requests.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

1. Create a dynamodb request
2. Instrument the handlers with the newrelic helper `nrawssdk.InstrumentHandlers(&req.Handlers)`
3. Send the request with DAX

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

Request sends without error and I see the trace in New Relic

[NOTE]: # ( Tell us what you expected to happen. )

## NR Diag results

panic!

[NOTE]: # ( Provide any other relevant log data. )

## Your Environment

- github.com/newrelic/go-agent/v3/integrations/nrawssdk-v1 v1.0.0

[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Reproduction case

[TIP]: # ( Link a sample application that demonstrates the issue. )

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by odannyc** [comment]
@RichVanderwal 

Please let me know if there is any additional information you need.

Thank you.

**Comment by RichVanderwal** [comment]
Hi @odannyc , thanks for your patience here! You're on the short list of support issues for us to get back to, and we'll be taking a look at this soon.

**Comment by RichVanderwal** [comment]
After some review, we've decided to check for a nil value here and skip adding the AWS Request ID span attribute if there's no response. PR forthcoming!

**Comment by odannyc** [comment]
Hi @RichVanderwal ,

I have a PR open for this issue here:

https://github.com/newrelic/go-agent/pull/291

**Comment by RichVanderwal** [comment]
Hello @odannyc ! We've included your PR  in the maintenance release of the Go Agent today. Let us know if you have any feedback, questions, or comments!
