### ISSUE TITLE
Handle DNS issues in client connection code

### ISSUE THREAD

**Issue by nr-swilloughby** [newrelic/go-agent#297]
## Summary
Investigate whether better handling of DNS issues can be performed in the [`getConnectBackoffTime()`](https://github.com/newrelic/go-agent/blob/master/v3/newrelic/internal_app.go#L184-L193) method.

## Desired Behaviour
The current behavior works, but perhaps could be more intelligent in seeking a way around the connection failure if it is caused by a DNS lookup issue.

**Comment by RichVanderwal** [comment]
One customer used the waitForConnection() call with poor DNS resolution when it would have been better if they had simply not called waitForConnection at all. We're putting it in the backlog for further consideration. See the Go Agent Team for more background if needed.
