### ISSUE TITLE
Zerolog Logs in Context

### ISSUE THREAD

**Issue by RichVanderwal** [newrelic/go-agent#298]
See attached external PR for implementing Logs in Context support for Zerolog.

**Comment by rwong2888** [comment]
Any traction on this @RichVanderwal ?

**Comment by RichVanderwal** [comment]
Good news, while I can't commit to dates, it's in the Go Agent Team's roadmap!

**Comment by iamemilio** [comment]
I am closing this issue to consolidate tickets about zerolog logs in context. We are still planning this work, but will now track it from the ticket that is already on our roadmap: https://github.com/newrelic/go-agent/issues/298
