### ISSUE TITLE
proposal: Add profiling with net/http/pprof

### ISSUE THREAD

**Issue by sergeylanzman** [newrelic/go-agent#30]
In ruby APM we have thread profiler. Work in 5 step
1. Clink on button start profiler on one if instance
2. Newrelic send command to server(newrelic magic)
3. On server newrelic agent collect samples.
4. Send samples to newrelic server(newrelic magic)
5. Analysing and visualisation in newrelic APM UI(newrelic magic)
This very cool fetcher in ruby.

Now I have idea for golang.
1. Clink on button start profiler on one if instance
2. Newrelic send command to server(same newrelic magic)
3. On server newrelic agent collect samples with net/http/pprof
4. Send samples to newrelic server(standard golang profile dump)
5. Analysing and visualisation in newrelic APM UI(same newrelic magic).

Standard golang profile dump include.
1. cpuprofile
2. memoryprofile
3. map of calls functions
4. Other good staff  about runtime application.

**Comment by willnewrelic** [comment]
Hey sergeylanzman

Thanks for the creative idea. I'm going to leave this open and add the "track-interest" label. I encourage all who would like this change to add a comment or thumbs up.

**Comment by robertnewrelic** [comment]
@sergeylanzman Wanted to get back to you since we last gave an update on this.  We've decided to start logging useful comments and suggestions as feature requests internally and closing out the pending issues.

Wanted to let you know we are doing that for this proposal, and aren't closing this out and just ignoring you!  We're always excited when customers come to us with ways to improve the agent or its interaction with the community.

We'll still need to internally review this proposal to see how much sense it makes for us / how to implement the feature if we do go forward with it.

**Comment by sergeylanzman** [comment]
@robertnewrelic Thank you! It's beneficial idea for your customers.

**Comment by frankgreco** [comment]
concerning go, the [go-agent](https://github.com/newrelic/go-agent) project requires custom implementation of New Relic (vendor specific) code. However, most (if not all) of what that agent is trying to do can be accomplished via the native golang profile without any custom new relic code. I imagine this would be **very** appealing to customers.

**Comment by kartavya-ramnani** [comment]
Hey,
I really like this idea and I am sure this will help all your go customers.

Now that go has really expanded and multiple production-impacting microservices are being written in golang, this feature is the need of the hour.

I would rather prefer this than painstakingly pass around context through every function. 

Please provide an update on this.

**Comment by jing-li-rocos** [comment]
Hi,

We are also looking at this feature. Is there any update? 

We also found out that Open-Telemetry collector supports the pprof exstion. I wonder if we can hook it to New Relic dashboard? 

https://github.com/open-telemetry/opentelemetry-collector/blob/master/extension/pprofextension/README.md

**Comment by RichVanderwal** [comment]
Hi @jing-li-rocos , thanks for your input! Yes, hooking up pprof to New Relic's profiling sessions would be very good to see. As the world moves over to OpenTelemetry, we'd also like to see this sort of functionality in OpenTelemetry for Go. 

Regarding the OpenTelemetry Collector, one could modify that pprof extension to output metrics for examination in New Relic. I don't see this in New Relic's roadmap anytime soon, but I'll raise this to the attention of our Product Manager to help them prioritize what we're working on next.

Of course, your ideas and PRs are welcome!

**Comment by rezanaipospos-xxi** [comment]
any update this? is very useful if new relic have profilling dashboard for go
