### ISSUE TITLE
Redis/external transaction support

### ISSUE THREAD

**Issue by jasonab** [newrelic/go-agent#31]
Would be great to be able to see how much time my app is spending in Redis, same as I do in my Python app.

**Comment by willnewrelic** [comment]
Hi @jasonab 

You can instrument Redis activity with the current datastore segment functionality.  In the beginning of the relevant function:

```go
	defer newrelic.DatastoreSegment{
		StartTime:          newrelic.StartSegmentNow(txn),
		Product:             newrelic.DatastoreRedis,
		Operation:          "GET",
	}.End()
```

Glancing quickly at https://github.com/go-redis/redis I do not believe that it will be straightforward for us to add higher level support for this package:  The interface is large and does not look like it has hooks for instrumentation.  Nonetheless, we will investigate more closely!

**Comment by jasonab** [comment]
Appreciate the response. One challenge I have is I'm using this with the Gin middleware you developed. That works great, but I don't have access to the transaction from the middleware. Can I create a new object that will be merged into the middleware one, or do I somehow need to get access to the original?

**Comment by willnewrelic** [comment]
Hi jasonab

You can give your handlers access to the transaction by adding it to the gin context.  Add this line to `nrgin.Middleware` function right before `c.Next()`:
```
c.Set("newrelic-txn", txn)
```
Then you can access it like so:
```
func handlerUsingTransaction(c *gin.Context) {
	t := c.Value("newrelic-txn")
	if txn, ok := t.(newrelic.Transaction); ok {
		defer newrelic.StartSegment(txn, "zap").End()
	}
	time.Sleep(500 * time.Millisecond)
}
```
We are hesitant to add this to the `nrgin` package because we plan on adding generic context support:  this will be done using a typed key (as encouraged [here](https://github.com/golang/go/issues/17293)), which Gin does not allow (only string keys), so we need to think about that.

**Comment by macnibblet** [comment]
Actually go-redis does have support for instrumentation, you simply use the client.WrapProcess but i'm not 100% sure how you would store it in newrelic.

```go

func NewrelicInstrumentation(client *redis.Client, nr newrelic.Application) {
	client.WrapProcess(func(oldProcess func(cmd redis.Cmder) error) func(cmd redis.Cmder) error {
		return func(cmd redis.Cmder) error {

			defer newrelic.DatastoreSegment{
				StartTime: newrelic.StartSegmentNow(nr.StartTransaction("redis", nil, nil)),
				Product:   newrelic.DatastoreRedis,
				Operation: cmd.String(),
			}.End()

			err := oldProcess(cmd)

			return err
		}
	})
}
```
