### ISSUE TITLE
Timing issue makes multiple harvests go to same "minute".

### ISSUE THREAD

**Issue by klauspost** [newrelic/go-agent#32]
After a recent deploy we observed that throughput was fluctuating greatly:

![throughput](https://cloud.githubusercontent.com/assets/5663952/21342052/13823780-c690-11e6-8e59-277693ae9212.png)

We could not find any reasonable explanation for this, and was unable to see this fluctuation on the load balancer. A re-deploy "fixed" the issue. Since we have recently upgraded to this client we took a look at it.

It seems like the harvester is relying on a [time.Ticker](https://github.com/newrelic/go-agent/blob/master/internal_app.go#L225) to start a harvest. However, this does not guarantee a steady time increment between each harvest. Looking at the logs for the problematic deploy, we observed that it was started "14:38:59".

So my best explanation is that due to timing issues a harvest would have a start time of ":59..." and some harvests a start time of ":00". It seems that when New Relic receives a harvest they are accumulated into 1 minute buckets. So if the last harvest started at :00 and another at :59 they are grouped together.

I would propose to use a constant 1 minute increment for harvests instead of relying on a ticker value that can fluctuate, so the "minute" always is the same.

Thank you for your great client. It is a huge upgrade.

**Comment by willnewrelic** [comment]
Hi Klaus

Yes, both the agent and our backed aggregator services work on 1 minute harvest schedules.  I have not heard of timing issues generating problems before.  Just to confirm that it is a metric harvest issue:  Do the Insights timeseries charts of your events show similar behavior?

I will discuss this issue with others internally.  Thanks for writing in.

**Comment by willnewrelic** [comment]
Hi Klaus

Upon looking at your chart, one of our support engineers believes that it is possible that the problem could be due to a lag issue on our backend.  Would you mind opening a support ticket if you would like us to investigate this further?

**Comment by klauspost** [comment]
Request #224783 opened.

**Comment by klauspost** [comment]
It seems like APM and Insights disagree on this. "Insights" having properly timed the input.

![apm](https://cloud.githubusercontent.com/assets/5663952/21420806/f7830aea-c82f-11e6-9eaf-93329e0e7e26.png)
![insights](https://cloud.githubusercontent.com/assets/5663952/21420805/f782edbc-c82f-11e6-890b-c693efd54b09.png)

Insights was selected for the same app.
