### ISSUE TITLE
nrgrpc integration is now reporting non-errors as errors in the UI

### ISSUE THREAD

**Issue by odannyc** [newrelic/go-agent#331]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

The latest version of the newrelic grpc integration package is reporting all grpc codes as errors. I believe the issue is here:

https://github.com/newrelic/go-agent/blob/master/v3/integrations/nrgrpc/nrgrpc_server.go#L85-L87

I think we should do filtering on grpc codes that are actual errors. Here is an example of what filtering another library does:

https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/logging/zap/options.go#L104-L144

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

- return a NotFound error code from the grpc server

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

- Does not show up in newrelic as an "error"

## NR Diag results

[NOTE]: # ( Provide any other relevant log data. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Reproduction case

[TIP]: # ( Link a sample application that demonstrates the issue. )

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by nr-swilloughby** [comment]
Thanks for raising this issue. We're looking into the best way to provide the greater granularity you are requesting so that instead of reporting any non-`OK` status as an error, we can selectively report them as errors, warnings, info, etc.

**Comment by RichVanderwal** [comment]
Releasing this very soon!

**Comment by RichVanderwal** [comment]
Hi @odannyc , we released the 3.14.0 version of the Go Agent, which has a configurable error handler for gRPC. 

We'd love it if you could give it a spin! [Here are the docs](https://pkg.go.dev/github.com/newrelic/go-agent/v3/integrations/nrgrpc#hdr-Server) for this new error handling.
