### ISSUE TITLE
Postgres integration example (nrpq) does not work

### ISSUE THREAD

**Issue by stephanebruckert** [newrelic/go-agent#340]
## Description

The nrpq integration does not send any metrics to the database dashboards

## Steps to Reproduce

The official example does not work https://github.com/newrelic/go-agent/blob/master/v3/integrations/nrpq/example/main.go

## Expected Behavior

It should send database metrics to the NR dashboards

## NR Diag results

https://pastebin.com/SyVStFHP

## Your Environment

```
go 1.16

require (
	github.com/google/go-cmp v0.3.1 // indirect
	github.com/lib/pq v1.10.2 // indirect
	github.com/newrelic/go-agent/v3 v3.13.0
	github.com/newrelic/go-agent/v3/integrations/nrpq v1.1.1
	golang.org/x/net v0.0.0-20210226172049-e18ecbb05110 // indirect
)
```

tried both locally on mac and on AWS ECS Fargate with latest docker image:

    FROM golang:alpine

## Additional context

 - issue already posted on https://discuss.newrelic.com/t/go-datastore-segments-nrpq-not-working-when-transactions-in-general-are-working-fine/152573, even though one of your staff members mentioned the issue couldn't be reproduced
 - also related to https://github.com/newrelic/go-agent/issues/242, as people seem to think that GORM is difficult to integrate, although the issue is the postgres integration IMO

**Comment by RichVanderwal** [comment]
HI Stephane, this is a puzzler. Thanks for getting the debug logging output. At first glance, according to those "Datastore" metrics in that log file, there should be something showing up in the UI, and it looks like the agent is doing what it's supposed to be doing. I'll take a closer look soon.

**Comment by stephanebruckert** [comment]
While switching between different tests, I was looking at the wrong app… my bad!

The nrpq example does work well.

Thanks for your quick response though
