### ISSUE TITLE
Metric Grouping Issue

### ISSUE THREAD

**Issue by kartik7153** [newrelic/go-agent#37]
I have two params in my URL. When I am wrapping that API call then it is showing url with differnet params. 
example:
My url - /v1/dr/{pramas1}/ds/{pramas2}

Actual request
/v1/dr/1/ds/2
/v1/dr/3/ds/4
/v1/dr/4/ds/3
/v1/dr/5/ds/6
/v1/dr/7/ds/8

On new relic dashboard it is showing something like this:
/v1/dr/*/ds/2
/v1/dr/*/ds/4
/v1/dr/*/ds/3
/v1/dr/*/ds/6
/v1/dr/*/ds/8

Can someone tell how to fix this issue. I am using go-agent

**Comment by robertnewrelic** [comment]
@kartik7153 Thanks for reaching out!  Are you still having an issue with MGI on the go-agent?

We have a docs page describing MGI in more detail: https://docs.newrelic.com/docs/agents/manage-apm-agents/troubleshooting/metric-grouping-issues

If you are still having this issue would you mind sharing some sample code to show how you are wrapping the API call?  I can help clarify why you are seeing an unexpected behavior.

**Comment by robertnewrelic** [comment]
I'm going to close this issue for the time being (in case your problem is already solved).  However, if I'm incorrect, please feel free to @ me and I will be happy to continue this thread and help you!
