### ISSUE TITLE
Using _integrations can result in type errors

### ISSUE THREAD

**Issue by nathany** [newrelic/go-agent#38]
I ran into an unusual issue today when adding `nrgorilla` to a project.

```
cannot use r (type *"github.com/myorg/myrepo/vendor/github.com/gorilla/mux".Router) as 
type *"github.com/gorilla/mux".Router in argument to nrgorilla.InstrumentRoutes
```

Where I work, we use [gvt](https://github.com/FiloSottile/gvt) to vendor code. It didn't vendor the `_integrations` code at all, likely due to the underscore prefix that tools tend to ignore. I'm guessing that it was intentional on your part to use the underscore prefix so users don't need to get/vendor every package and dependency in that folder.

The rather strange error above is because Go was reaching outside of the vendor folder for nrgorilla while go-agent itself was vendored. That resulted in several type errors such as the one above.

There are a few possible solutions I can think of:
* Document this so that it's less confusing for others in the future.
* Having several separate repos for extensions would provide an immediate solution that wouldn't require the underscore prefix, but it may be a bit annoying to maintain.
* In the longer term, once people adopt [dep](https://github.com/golang/dep), you will be able to remove the underscore prefix from `_integrations` and have everything work nicely. The reason is that dep looks at the import graph, so it can determine whether it needs to vendor the dependencies of nrgorilla based on whether or not it's used.

**Comment by curtisallen** [comment]
Any workarounds for this? I ran into the same thing today.

**Comment by nathany** [comment]
No workaround with `gvt` since it doesn't copy in the _integrations or allow vendoring them separately.

```
❯ gvt fetch github.com/newrelic/go-agent/_integrations/nrgorilla/v1
2017/04/04 15:59:53 command "fetch" failed: github.com/newrelic/go-agent/_integrations/nrgorilla/v1 or a parent of it is already vendored
```

So I just manually copied the `_integrations` folder (or a subset of it) into my project's vendor folder.

**Comment by robertnewrelic** [comment]
@nathany Thanks for pointing out the issue you ran into with gvt.  I'm not too surprised it had an issue with the underscore.  For now your workaround appears to work for the immediate.  I'm going to go ahead and close out this issue since there is an immediate resolution possible.

We'll keep track of this problem internally and discuss possible alternatives as we prep additional releases.  We in the Go agent team have been keeping our eyes on dep.  Though, obviously, that's further looking down the road.
