### ISSUE TITLE
New Relic integration with gqlgen

### ISSUE THREAD

**Issue by ravikumarjs-foyernet** [newrelic/go-agent#380]
how to integrate new relic with gqlgen?

**Comment by RichVanderwal** [comment]
Hi @ravikumarjs-foyernet , thanks for asking! The answer depends on exactly what you want to instrument -- the process of generating code, or the resulting graphql code, or something else.

If you know the code well enough, you can write your own instrumentation using the basics that the Go Agent provides, following the [documentation here](https://docs.newrelic.com/docs/agents/go-agent/instrumentation/).

However, if you'd like this to be a feature request, let us know exactly what you want and we'll forward this to Product Management so we can prioritize and dig in.
