### ISSUE TITLE
Always got error `msg="unable to end segment" component=newrelic name=async "transaction has already ended"

### ISSUE THREAD

**Issue by adzimzf** [newrelic/go-agent#382]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
I tried to create a segment of goroutine, I've followed [this doc](https://docs.newrelic.com/docs/agents/go-agent/features/trace-asynchronous-applications/). but I always got error `msg="unable to end segment" component=newrelic name=async reason="transaction has already ended"`

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
here's my sample code
```go
txn := app.StartTransaction("some-trx")
defer txn.End()

go func(txn *nr.Transaction) {
	defer txn.StartSegment("async").End()
	time.Sleep(100 * time.Millisecond)
}(txn.NewGoroutine())

ctx = newrelic.NewContext(ctx, *txn)
err = doSomethingElse(ctx)
```

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
running without error

[NOTE]: # ( Tell us what you expected to happen. )

## NR Diag results

[NOTE]: # ( Provide any other relevant log data. )

## Your Environment
Linux Ubuntu 20
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Reproduction case

[TIP]: # ( Link a sample application that demonstrates the issue. )

## Additional context
my use-case is when the user generating a report, the report will be generated async. I want to create segment for the async process.

[TIP]:  # ( Add any other context about the problem here. )

**Comment by RichVanderwal** [comment]
Hi @adzimzf , thanks for writing in! We'll get to this as soon as possible, but have you considered opening up a [Support Ticket ](https://support.newrelic.com/)or an [Explorer's Hub](https://discuss.newrelic.com/) (that's our community forum) post about this? You might get faster results from the community or our dedicated support staff.

**Comment by adzimzf** [comment]
Hi @RichVanderwal thanks for the answer.
I'll try to float there as well

**Comment by RichVanderwal** [comment]
Hi @adzimzf , have you received any answers from your Support Ticket or Explorer's Hub post?

Looking at your code, there's a chance you might be ending the transaction before that 100ms segment has a chance to end. When the transaction finishes, we package up all the segments within and any other data for sending to New Relic. If there are unfinished segments during that time, the agent logs that error you're seeing and those segments are dropped.

This _does_ mean that long-running asynchronous tasks are difficult to track with this agent, unless you modify the transaction's end to accommodate your long-running task.

I hope this answers any questions you have. If you'd like to turn this issue into a feature request, let me know and I'll make sure our Product Management team hears about it.

**Comment by adzimzf** [comment]
Hi there,
sorry for very late response,
the solution is by creating a new transaction when spawning a new goroutine then insert the tracing headers  to transaction.
