### ISSUE TITLE
this trace has no root span

### ISSUE THREAD

**Issue by willie** [newrelic/go-agent#385]
All of my distributed traces in my app have the error: "This trace has no root span" and "X orphan trace fragments" and I cannot figure out why.

## Description

With my Go apps using the go-agent, my distributed trace details consistently tell me that my traces have "This trace has no root span" and "X orphan trace fragments". I assume that these are errors in my instrumentation, but I'm not sure.

## Steps to Reproduce

Handlers are wrapped with `newrelic.WrapHandle`
Per request transactions are identified by `txn := newrelic.FromContext(r.Context())`
Segments are created by `defer newrelic.FromContext(ctx).StartSegment("NAME").End()`

FYI: I am changing the name of the transaction in my handler after the segments are created, but before returning control back to `newrelic.WrapHandle` 

## Expected Behavior

I don't expect "This trace has no root span" and "X orphan trace fragments" errors and I don't know how to resolve them. Docs state: "No root span. Missing the root span, which is the first operation in the request. When this happens, the span with the earliest timestamp is displayed as the root."

I'm expecting `StartTransaction` to, in essence, create a root span -- is that incorrect? Do I have to manually do this?

## Your Environment

`github.com/newrelic/go-agent/v3 v3.15.0`
`go1.17`

## Additional context

My application init is: 

```
newrelic.NewApplication(
		newrelic.ConfigAppName(appName),
		newrelic.ConfigLicense("xxx"),
		newrelic.ConfigDistributedTracerEnabled(true),
		func(config *newrelic.Config) {
			config.CrossApplicationTracer.Enabled = false
		},
	)
)
```

**Comment by RichVanderwal** [comment]
Hello @willie ,

Thanks for writing in, and sorry for the delay in getting back to you!  This issue fell between the cracks, and I'd like to help resolve this quickly for you.

I'm glad you mentioned that you're renaming the transaction soon after beginning it -- we'll check to make sure that this doesn't keep the agent from reporting the correct traceIDs to allow the identification of a root span. Do you have a quick reproduction to help speed this along?

**Comment by Ak-x** [comment]
Hello @willie, is this still an issue for you? Please let us know if you would like our team to look into this further.

This issue will be automatically resolved within 30 days if we have no response.
