### ISSUE TITLE
nrpgx - Support direct pgx calls

### ISSUE THREAD

**Issue by ghmj2417** [newrelic/go-agent#386]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
Per [nrpgx.go](https://github.com/newrelic/go-agent/blob/master/v3/integrations/nrpgx/nrpgx.go), it states:
```
// USING WITH DIRECT PGX CALLS WITHOUT DATABASE/SQL
//
// This mode of operation is not supported by the nrpgx integration at this time.
//
```
[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behaviour
Support direct pgx calls

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Additional context
We utilize pgx directly and it would be nice to see the metrics in New Relic.  Particularly, we utilize the pgx CopyFrom functionality.

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by nr-swilloughby** [comment]
We're actively looking into this. Thanks for adding your voice to let us know the level of interest in having this enhancement.

**Comment by ghmj2417** [comment]
Thank you.  Please let me know if you need anymore information.

**Comment by talpert** [comment]
This would help us a lot as well! Seems like the pgx author is really pushing people to use the pgx interfaces, so it would be awesome to see support for this in the agent. https://github.com/jackc/pgx#choosing-between-the-pgx-and-databasesql-interfaces

**Comment by nr-swilloughby** [comment]
Thanks for continuing to express interest. It does help us by influencing what projects we prioritize here. We should have something addressing this before long.

**Comment by nr-swilloughby** [comment]
This has been implemented in the most recent agent release.
