### ISSUE TITLE
concurrency and transactions

### ISSUE THREAD

**Issue by bhcleek** [newrelic/go-agent#39]
The documentation for `NewRoundTripper` and `Transaction` explicitly say that they should only be used in a single goroutine, but looking at the code it doesn't appear that there would be any problems using them from multiple goroutines. We have a web application that may spawn multiple goroutines to make requests to other services from a single source request. Ideally, we would not have to create a transaction per subrequest. Is the documentation correct, or are Transaction and `NewRoundTripper` safe for use from multiple goroutines?

**Comment by bhcleek** [comment]
I should clarify that the lifetime of the goroutines that make the subrequests is always within the lifetime of the goroutine that starts them.

**Comment by cmiller01** [comment]
This use case would be very helpful for us as well. @bhcleek in our initial testing of the tracing we were passing around the same `Transaction` within new goroutines, and as the docs point out this doesn't really work. It appears that data was being intermittently dropped.

**Comment by peterhellberg** [comment]
I would also be interested in knowing more about how to deal with this use-case (_multiple goroutines, all with a shorter lifetime than the original goroutine_)

If this isn't possible, how about supporting sub-transactions?

**Comment by astormnewrelic** [comment]
@bhcleek Good eye!  Unfortunately, those comments (while a little unclear) are accurate.  Without getting too deeply into it, both `NewRoundTripper` and `Transaction` weren't explicitly designed with concurrency in mind, and spawning off go routines that access/manipulate the same Transaction can (sometimes) introduce subtle timing/accuracy issues with segments (and possibly other places? )

That said (to echo @cmiller01 and @peterhellberg, thanks both!) better concurrency support would be a pretty sweet feature to have.  We're logging/tracking it internally and while we can't promise a delivery date it is on our radar.  

We're closing this issue out, but if you still have questions don't hesitate to chime in below or via another one of our [support channels](https://support.newrelic.com/).
