### ISSUE TITLE
Instrument outgoing AWS SQS calls

### ISSUE THREAD

**Issue by ArchieY393** [newrelic/go-agent#392]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

The example shown here is for short lived process: https://github.com/newrelic/go-agent/blob/v3/integrations/nrawssdk-v2/v1.2.0/v3/integrations/nrawssdk-v2/example/main.go. 

However for long running servers, it is not ideal to create transactions in main() as the main() never ends(or long running) and the transaction would appear on newrelic UI only after it's been ended.

For long running servers, how to instrument the AWS SQS outbound calls ? Or the question can be reframed, can the 'AppendMiddlewares' be made to accept transaction for every SQS call the server process. 

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## See the outbound SQS call for each transaction

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by ArchanaY** [comment]
Do you've any examples for long running servers ?

**Comment by ArchieY393** [comment]
Closing this as it's working as expected on AWS sdk v2
