### ISSUE TITLE
instrument third party libraries

### ISSUE THREAD

**Issue by ArchieY393** [newrelic/go-agent#393]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

There's no flexibility to instrument third party libraries. Even though Go has tons of third libraries to use, it's boiling down to the fact to pick a library which supports newrelic. For eg. I use kivik/v4, it does accept the ctx for every interface, but it can't be instrumented like we do for SQL. 

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

To be able to instrument third party libraries

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by nr-swilloughby** [comment]
You can add code (see our Guide.md) to add custom instrumentation to your database calls, but if you are asking for new integrations to be written, we can of course add specific requests (such as kivik/v4) to our list of future integrations to be written. 
Let us know if this is in fact what you'd like and we'll start the process to do that.
As far as flexibility, though, it's there in the product; it just needs some code to be written by you or by us (such as by creating an integration).

**Comment by Ak-x** [comment]
Hello @ArchieY393, is this still an issue for you? Please let us know if you would like our team to look into this further. 

This issue will be automatically resolved within 30 days if we have no response.

**Comment by Ak-x** [comment]
Closing this issue as we have had no response, please feel free to comment or re-open if this issue persists.
