### ISSUE TITLE
non-database/sql-based pgx integration

### ISSUE THREAD

**Issue by nr-swilloughby** [newrelic/go-agent#396]
Create a new integration to instrument the jackc/pgx postgres database package, using the direct database manipulations provided by that package, not the database/sql compatibility ones.

**Comment by amcd00** [comment]
Just interested to know if this was still progressing. Using database/sql in production isn't the first choice anymore vs using jackc/pgx directly.

**Comment by nr-swilloughby** [comment]
It's still on our radar. Comments like yours do help us to know how important this feature is for our customers, so thanks for adding that!

**Comment by nr-swilloughby** [comment]
This is implemented in the `nrpgx5` integration.
