### ISSUE TITLE
v3/integrations/nrpkgerrors: support errorAttributer interface

### ISSUE THREAD

**Issue by eightnoteight** [newrelic/go-agent#409]
currently nrpkgerrors supports `errorClasser` even though `pkg/errors` doesn't support `errorClasser`. I'm assuming that this is done so that any extensions on top of `pkg/errors` that add support for `errorClasser` will continue to work with nrpkgerrors.Wrap as well.

but unfortunately the same is not true for `errorAttributer` interface. nrpkgerrors wraps the error but if that error supports `errorAttributer` then that information would get lost.

## Desired Behaviour

if any error that supports `errorAttributer` interface is wrapped by `nrpkgerrors.Wrap` then the final wrapped error should also support `errorAttributer` interface.

## Possible Solution

add a call to a helper function below this line [here](https://github.com/newrelic/go-agent/blob/5be716d8cd050352243214f49b55042c652e2df7/v3/integrations/nrpkgerrors/nrpkgerrors.go#L86) that checks if the incoming error supports errorAttributer interface, if so then use the attributes given by that error.

**Comment by RichVanderwal** [comment]
HI @eightnoteight , thanks for your thorough description and solution suggestion! I'll make sure our Product Managers sees this so we can help prioritize our product roadmap for next year.
