### ISSUE TITLE
How to handle multiple mux routers

### ISSUE THREAD

**Issue by kamal-github** [newrelic/go-agent#41]
I am using gokit, and want to monitor multiple routers, as i am creating multiple routers in different transport.go file.

I want to achieve like this or let me know the alternative way.
For instance: `nrgorilla.InstrumentRoutes(r, r1, r2, app)` ; where r, r1 ... are mux routers.

**Comment by kamal-github** [comment]
Can any one help please?

**Comment by astormnewrelic** [comment]
Thanks for your feedback @kamal-github.  Could you clarify what you're asking here?  i.e. are you suggesting some refinements for our Gorilla Web Toolkit API?  Or are you trying to use our existing API and running into problems?

Re: Multiple routers -- it might help us understand you better if you could provide a little more context on what you're trying to do here and how you're using multiple routers.  That is, in our existing API, we wrap the gorilla router with a syntax that looks like this

    r := mux.NewRouter()
    r.Handle("/", makeHandler("index"))
    http.ListenAndServe(":8000", nrgorilla.InstrumentRoutes(r, app))

Without our instrumentation, mux routing would look like this

    r := mux.NewRouter()
    r.Handle("/", makeHandler("index"))
    http.ListenAndServe(":8000", r)
    
So, even without our instrumentation, Go expects a single router per port.  You could do something like this    
    
    r1 := mux.NewRouter()
    r1.Handle("/foo", makeHandler("foo"))
    
    r2 := mux.NewRouter()
    r2.Handle("/bar", makeHandler("bar"))
        
    http.ListenAndServe(":8000", nrgorilla.InstrumentRoutes(r1, app))
    http.ListenAndServe(":8001", nrgorilla.InstrumentRoutes(r2, app))

But it doesn't seem like you're asking about using multiple routers on different ports.  Given all that context, if you can clarify what you're trying to do we'll be a much better position to help.  

Also -- while we're happy ot hear about bug reports/fixes via PRs here, the fastest way to get general support for New Relic agents (including the go agent) is via the official support channels over at https://support.newrelic.com/ -- The existing knowledge base articles have a bunch of solutions to common problems. If you can't find what you're looking for there opening a ticket and/or opening a thread on the support forums is the best way to get your support questions in front of folks ready to help. 

Regardless, thank you for your patience as we get this resolved.

**Comment by astormnewrelic** [comment]
Hey @kamal-github -- we didn't hear back from you on this so we're going to close this issue out.  If we've done this prematurely our apologies -- please don't hesitate to reach out via one of the [aforementioned support channels](https://support.newrelic.com/).
