### ISSUE TITLE
newrelic.WrapHandle not being invoked when path variable is present in API endpoint

### ISSUE THREAD

**Issue by kamal-github** [newrelic/go-agent#42]
Its not calling `newrelic.WrapHandle` function if Path variable is present in API endpoint. while WrapHandle function being invoked when there is no path variable.

`http.Handle(newrelic.WrapHandle(app, "/api/v1/search/{entityType}", searchHandler)`

Could you please fix this or let me the know the quick solution? Its urgent.

**Comment by astormnewrelic** [comment]
Thanks for your feedback @kamal-github.  We're more than happy to help get you where you need to be -- but we're not 100% clear what issue you're running into.  Your code sample is using a path variable (`{entityType}`) but (appears to?) be using the standard GoLang HTTP package/library.  That standard GoLang HTTP package/library doesn't (to my knowledge) support those sort of path variables.  If you could provide a little more context on your code, what your'e trying to accomplish, what you tried, what you expected to happen, and what actually happened, we'll be in a much better position to help you.

Also -- if this is a general support request, the way to get the *fastest* support is to use the official support channels over at https://support.newrelic.com/ -- The existing knowledge base will often have solutions to common problems, and if not opening a ticket and/or opening a thread on the support forums is the best way to get your support questions in front of folks ready to help.

**Comment by astormnewrelic** [comment]
Hey @kamal-github -- we didn't hear back from you on this so we're going to close this issue out.  If we've done this prematurely our apologies -- please don't hesitate to reach out via one of the [aforementioned support channels](https://support.newrelic.com/).
