### ISSUE TITLE
Duplicate Errors with NoticeError

### ISSUE THREAD

**Issue by dralph3344** [newrelic/go-agent#426]
## Summary

While called out as expected behavior, it would really be ideal to not have duplicate errors. We see things like 500s / Internal Server error duplicates, and would like that rolled up just in one error report. 

## Desired Behaviour

One error reported, rather than two.

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

This would be an ideal improvement to our user experience in the  NR UI, and in investigation of errors.

**Comment by RichVanderwal** [comment]
Hi @dralph3344 , thanks for this issue! We certainly want to steer clear of creating duplicate errors.

Can you show us an example of this in the UI, perhaps with some agent logs so we can reproduce that here?

**Comment by Ak-x** [comment]
Hello @dralph3344, is this still an issue for you? Please let us know if you would like our team to look into this further.

This issue will be automatically resolved within 30 days if we have no response.

**Comment by nr-swilloughby** [comment]
Closing this issue per previous comments in the thread. If this issue pops up again for you or you do find you need additional help in the future, feel free to reach out again and we'll take another look at that time.
