### ISSUE TITLE
unit tests for v3/integrations/nrawssdk-v1 are broken

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#432]
The unit tests for nrawssdk-v1 are broken. This makes it very difficult to submit any fixes for that module.

One of the problems is that the code is expecting to find the AWS request id in in the _request_ header, but the test framework only sets it in the _response_ header. I believe the tests are correct here, meaning the code is actually broken. In particular, it was broken by #291.

**Comment by Ak-x** [comment]
This should be resolved by the completion of: https://github.com/newrelic/go-agent/pull/433

**Comment by Ak-x** [comment]
Closing this per #433
