### ISSUE TITLE
Document best way to instrument GORM

### ISSUE THREAD

**Issue by RichVanderwal** [newrelic/go-agent#438]
Customers are getting good results by instrumenting the underlying database layer in the conversation in [this issue](https://github.com/newrelic/go-agent/issues/242). This seems important, since eight people 👍 'd that issue.

Review the best way to document this to help customers fastest. Also, consider extending this documentation to cover tools other than just GORM.

**Comment by th0th** [comment]
Where can I find the related documentation?
