### ISSUE TITLE
How to run without providing a license key?

### ISSUE THREAD

**Issue by relistan** [newrelic/go-agent#46]
In local development mode, in CI testing, etc we don't want to send metrics to New Relic. There is not an obvious way to disable the agent on startup. If you don't create an application, the instrumentation blows up all over the place with nil pointer errors. If you don't provide a license it returns an error from `NewApplication()`. If you provide an invalid license it still tries to talk to New Relic. So, I've put together some stubs that implement the `Application` and `Transaction` interfaces, but this is fairly ugly and subject to breakage. Is there an obvious way to do this now that I'm missing?

**Comment by willnewrelic** [comment]
Hi Karl

If you set `Config.Enabled` to false, the license check will not be performed and the application returned will act as a non-nil stub.

**Comment by relistan** [comment]
@willnewrelic awesome, thanks man! I looked through all that and somehow missed that setting.
