### ISSUE TITLE
GoAgent version not being updated on version.go file

### ISSUE THREAD

**Issue by cristian-hexad** [newrelic/go-agent#461]
## Description
When trying to see the go agent version on newrelic I always see version 2.16.4 even though I am using your last version of the repo. The issue appears to be on file: version.go (https://github.com/newrelic/go-agent/blob/master/version.go) not being updated since it contains the following lines:

	const (
		major = "2"
		minor = "16"
		patch = "4"

		// Version is the full string version of this Go Agent.
		Version = major + "." + minor + "." + patch
	)

And it has not been updated since 18 Jun 2020.
Could you confirm my assumption please?

**Comment by nr-swilloughby** [comment]
That `version.go` file belongs to the v2 agent which is no longer being developed. The current agent is the v3 one, in the `v3` subdirectory. It has a `version.go` file https://github.com/newrelic/go-agent/blob/master/v3/newrelic/version.go which shows the current version 3.15.2.
