### ISSUE TITLE
W3C Trace Context Propagation Does Not Follow Specification

### ISSUE THREAD

**Issue by blakeroberts-wk** [newrelic/go-agent#463]
## Description

https://www.w3.org/TR/trace-context/#header-name
> Vendors MUST expect the header name in any case (upper, lower, mixed), and SHOULD send the header name in lowercase.

However, the agent only recognizes and only supports the form `Traceparent`.

https://github.com/newrelic/go-agent/blob/06c801d5571056abac8ac9dfa07cf12ca869e920/v3/newrelic/distributed_tracing.go#L335

https://github.com/newrelic/go-agent/blob/d628ce87042ab6b3a2da6aba81c130fcb0d4d6dc/v3/newrelic/transaction.go#L461-L466

This same issue exists for the trace state header.

## Steps to Reproduce

N/A

## Expected Behavior

N/A

## NR Diag results

N/A

## Your Environment

N/A

## Reproduction case

N/A

## Additional context

N/A

**Comment by v3n** [comment]
I don't think this is a bug: this is expected Go behavior. All header keys in Go are canonicalized header keys with textproto.CanonicalMIMEHeaderKey()](https://pkg.go.dev/net/textproto#CanonicalMIMEHeaderKey).

The only exception would be if you used a struct constructor to initialize http.Header by hand, but that would be an application bug [according to the stdlib docs](https://pkg.go.dev/net/http#Header):

> The keys should be in canonical form, as returned by CanonicalHeaderKey.

**Comment by blakeroberts-wk** [comment]
This is true, I understand your point of view. The code where I'm seeing this issue does use `headers.Add()` which as you've mentioned should append the headers in canonicalized form. I guess I jumped the gun here and there must be another issue at play. I will have to continue digging.

Aside: it is strange to me to only sometimes enforce canonicalized form:
https://github.com/newrelic/go-agent/blob/06c801d5571056abac8ac9dfa07cf12ca869e920/v3/newrelic/distributed_tracing.go#L251 vs https://github.com/newrelic/go-agent/blob/06c801d5571056abac8ac9dfa07cf12ca869e920/v3/newrelic/distributed_tracing.go#L335

**Comment by Ak-x** [comment]
Closing this issue, please open this up again if this needs to be addressed.
