### ISSUE TITLE
Segments without transaction variable

### ISSUE THREAD

**Issue by ventayol** [newrelic/go-agent#47]
Is it possible to create segments without having the Transaction variable?
We want to monitor different areas of the code but if we need to have the Transaction variable, we need to modify a lot our code and start sending the variable through a lot of functions to have it where is needed.

Is there any way to solve this issue?

**Comment by peterhellberg** [comment]
@ventayol You could put the `newrelic.Application` or `newrelic.Transaction` in `context.Context`.

This can for example be done with http://github.com/smacker/newrelic-context or my own package https://github.com/TV4/nrcontext (since there isn't support for this in **go-agent** directly)
