### ISSUE TITLE
can not configure max samples stored for custom events

### ISSUE THREAD

**Issue by iamemilio** [newrelic/go-agent#476]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

It is a standard protocol for other agents to allow users to configure the number of custom events stored with a configuration setting named: `"custom_insights_events.max_samples_stored": 1000,`. This option is not available in the Go agent config.

**Comment by mirackara** [comment]
Closing Issue per https://github.com/newrelic/go-agent/wiki/Release-Checklist
