### ISSUE TITLE
need new release of github.com/newrelic/go-agent/v3/integrations/nrawssdk-v1

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#499]
github.com/newrelic/go-agent/v3/integrations/nrawssdk-v1@v1.0.1 is incompatible with github.com/newrelic/go-agent/v3@v3.16.0. (This is due to the breaking change I mentioned in #433.) Please release a new version of this integration.

> \# github.com/newrelic/go-agent/v3/integrations/nrawssdk-v1
../../pkg/mod/github.com/newrelic/go-agent/v3/integrations/nrawssdk-v1@v1.0.1/nrawssdk.go:36:23: cannot use hdr (type http.Header) as type *http.Response in argument to awssupport.EndSegment

**Comment by nr-swilloughby** [comment]
We can set up a small release with this change ASAP.

**Comment by rittneje** [comment]
@nr-swilloughby Just wanted to follow up on this.

**Comment by nr-swilloughby** [comment]
We're putting together a small release this week with this and a couple of other necessary version updates.

**Comment by nr-swilloughby** [comment]
Bumped the version number to v1.1.0 (was 1.0.1)
