### ISSUE TITLE
[NFR] Custom metric support

### ISSUE THREAD

**Issue by ovr** [newrelic/go-agent#50]
Hey!

I cannot find it inside any documentation for this library, I find only attributes but it's only for Transacations

Thank

**Comment by ovr** [comment]
ping @willnewrelic

**Comment by robertnewrelic** [comment]
Hey @ovr !  I wanted to follow up with you to let you know that support for custom metrics will be available in our next release.  I do not yet have an ETA for that release, but know that it will be soon!

**Comment by willnewrelic** [comment]
Hi All

We just released custom metrics in https://github.com/newrelic/go-agent/releases/tag/v1.10.0

Check out the `RecordCustomMetric` method in `Application` !

Thanks for your patience.
