### ISSUE TITLE
update go.mod for v3/integrations/nrawssdk-v1

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#510]
The nrawssdk-v1 module actually relies on v3.16.0 of the super module. Please update its go.mod file accordingly.

https://github.com/newrelic/go-agent/blob/a0f3666caec5305df9768dc177c553a1a8d75d3b/v3/integrations/nrawssdk-v1/go.mod#L11

**Comment by nr-swilloughby** [comment]
Thanks for catching that. We'll put out an update which includes that change.

**Comment by sdbedi** [comment]
This PR should fix it:
https://github.com/newrelic/go-agent/pull/525

**Comment by rittneje** [comment]
closing because this is fixed now (although a new release of the nrawssdk-v1 module is pending)
