### ISSUE TITLE
Update dependency on gin to 1.7.7

### ISSUE THREAD

**Issue by nr-swilloughby** [newrelic/go-agent#513]
Versions of gin less than 1.7.7 have a reported security vulnerability [HTTP response splitting](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGINGONICGIN-1041736). 

Update the `go.mod` file for the `nrgin` integration to require at least version 1.7.7 of gin.

**Comment by sdbedi** [comment]
PR opened: https://github.com/newrelic/go-agent/pull/514
