### ISSUE TITLE
Show query parameters in SQL automatic instrumentation

### ISSUE THREAD

**Issue by iamemilio** [newrelic/go-agent#520]
When customers instrument queries using our datastore plugins, they expect aspects of that query like WHERE clauses and other parameterized queries to show up in their data. This was left out of the initial implementation of the sql instrumentation library by design, but is an incremental next step towards improving the value provided by this product.

Here is an example query:

```go
_ "github.com/newrelic/go-agent/v3/integrations/nrpq"

Postgres, err = gorm.Open(postgres.New(postgres.Config{
		DriverName: "nrpostgres",
		DSN:        psqlInfo,
	}), &gorm.Config{
		NamingStrategy: schema.NamingStrategy{
			SingularTable: true,
		},
	})

gormTransactionTrace := relic.NewRelicApp.StartTransaction("Create Marketplace")
gormTransactionContext := newrelic.NewContext(context.Background(), gormTransactionTrace)
tracedDB := db.Postgres.WithContext(gormTransactionContext)
tracedDB.Take(&marketplace, "column = ?", column)
```

In this case, the data only shows that a SELECT was executed on a specific database, and excludes the WHERE clause and additional query parameters.

**Comment by Ak-x** [comment]
Feature Request is to allow queries in NR1 with both Postgres + Gorm.
cc: @ak-war

**Comment by Ak-x** [comment]
Closing as a duplicate issue.
