### ISSUE TITLE
Segments doesn't appear on NewRelic

### ISSUE THREAD

**Issue by henriqueholanda** [newrelic/go-agent#54]
I'm trying to create a Segment in some piece of my code, but it doesn't appear on NewRelic.
I followed the documentation, I implemented all the exemples, but it doesn't works.
All the other things its ok (Transactions, Errors, Web External).

Somebody has some problem with that?
Have some particularity to do this?

**Comment by astormnewrelic** [comment]
@henriqueholanda Thank you for using the New Relic Go Agent! Don't worry, we'll get you where you need to be ASAP.  

First -- we have a sample application that covers basic usage of of the APIs provided by the SDK.  You can run this application by exporting a `NEW_RELIC_LICENSE_KEY`, setting your application name in `examples/server/main.go`, and then running the following command.

    $ run examples/server/main.go
    
This application implements a simple web server on port `8000` with URLs that exercise certain API features.  It looks like the following URL exercises the `StartSegment` method

    http://localhost:8000/segments

and the following URL exercises the `ExternalSegment` method

    http://localhost:8000/external      

So, for starters, I'd give the sample application a try if you're trying to understand segments, or troubleshoot how they should work with your application.

Second -- if you're having trouble with your account, or have a question generally about how New Relic's functionality works, the fastest way to get support is via New Relic's [https://support.newrelic.com/](https://support.newrelic.com/) website.  We often have knowledge base articles that will address your questions, and if we don't then opening a support ticket or [posting a question on the forums](https://discuss.newrelic.com/) gets it in front of the most people with the right knowledge to help you out. 

We're going to close this issue out (as we try to keep GitHub features like issues and PRs reserved for issues with the code itself), but if you need additional help please don't hesitate reach out via the aforementioned support channels mentioned.  Also, if we've misread your intent and you *have* uncovered an issue with the go agent/sdk, please don't hesitate to let us know.
