### ISSUE TITLE
App crash with "Fatal error: concurrent map read and map write" when calling SetWebRequestHTTP

### ISSUE THREAD

**Issue by nicoroy2561** [newrelic/go-agent#549]
## Description

My production app just crashed with the following error, roughly 4-5 hours after integrating the newrelic agent (has worked flawlessly until now):

```
fatal error: concurrent map read and map write

goroutine 99368 [running]:
net/textproto.MIMEHeader.Get(0xc00574c090, {0xd4c658?, 0xc00574c090?})
        .../go/1.19/libexec/src/net/textproto/header.go:34 +0x45
net/http.Header.Get(...)
        .../go/1.19/libexec/src/net/http/header.go:50
github.com/newrelic/go-agent/v3/newrelic.acceptPayload(0x7f123b5d3bb8?, {0xc0007bb097, 0x7}, 0xb67590d6b04?)
        /.../github.com/newrelic/go-agent/v3@v3.18.0/newrelic/distributed_tracing.go:303 +0x3d
github.com/newrelic/go-agent/v3/newrelic.(*txn).acceptDistributedTraceHeadersLocked(0xc005d76000, {0xd4522d?, 0xacec31?}, 0x14d9a20?)
        /.../github.com/newrelic/go-agent/v3@v3.18.0/newrelic/internal_txn.go:1194 +0x23b
github.com/newrelic/go-agent/v3/newrelic.(*txn).SetWebRequest(0xc005d76000, {0xc00574c090, 0xc0052ace10, {0xc00617a5a1, 0x3}, {0xd4522d, 0x4}, {0x0, 0x0}
})
        /.../github.com/newrelic/go-agent/v3@v3.18.0/newrelic/internal_txn.go:218 +0x145
github.com/newrelic/go-agent/v3/newrelic.(*Transaction).SetWebRequest(0xc006779260, {0xc00574c090, 0xc0052ace10, {0xc00617a5a1, 0x3}, {0xd4522d, 0x4}, {0
x0, 0x0}})
        /.../github.com/newrelic/go-agent/v3@v3.18.0/newrelic/transaction.go:202 +0x7b
github.com/newrelic/go-agent/v3/newrelic.(*Transaction).SetWebRequestHTTP(0xc000b09676?, 0xd47b7c?)
```

The code causing the issue is the following:
```
	txn := nr.App.StartTransaction("XXX")
	txn.SetWebRequestHTTP(r)
```
It seems to work fine most of the time, but it did trigger this issue and crash the whole app.

## Steps to Reproduce

Running the code above

## Expected Behavior

No crashes

## Your Environment

go version go1.19 linux/amd64
newrelic v3@v3.18.0

**Comment by iamemilio** [comment]
Thanks for reporting,  I'll try to get a reproducer working and see if can troubleshoot this. Is calling the code you posted a high probability reproducer?

```go
txn := nr.App.StartTransaction("XXX")
txn.SetWebRequestHTTP(r)
```

**Comment by nicoroy2561** [comment]
Thank you for following up on this.

Sadly, no. It seems a very rare occurrence.
Probably hard to notice otherwise, but the fact that it can lead to a whole app crash makes it a big issue.

Currently I'm using a workaround: 
```
	txn.SetWebRequest(newrelic.WebRequest{
		Header:    nil, //r.Header, -- nil due to it causing crashes
		URL:       nil, //r.URL,
		Method:    r.Method,
		Transport: newrelic.TransportHTTPS,
		Host:      r.Host,
	})
```
Which does seem to "do the trick". 
As such, I was only ever able to produce the stacktrace above (deployed this workaround to my server right after that).

**Comment by nicoroy2561** [comment]
Forgot to answer to your questions.

nr.App is a *newrelic.Application, setup by a separate function once when the server is run.

`txn := nr.App.StartTransaction("XXX")` and subsequent calls to txn are indeed made asynchronously from different threads (whenever each conn makes its own requests). I don't think there's any code making asynchronous use of Conn, but I can't be sure due to using a websocket library.

**Comment by iamemilio** [comment]
Reproduced and captured in this test case. Thanks again for reporting. We will try to get a fix out the door for this as soon as we are able.


```go
func TestAsyncTxn(t *testing.T) {
	app := testApp(replyFn, cfgFn, t)
	threads := 2

	wg := sync.WaitGroup{}
	wg.Add(threads)

	doTxnStuff := func(app *Application, wg *sync.WaitGroup, name string) {
		txn := app.StartTransaction(name)

		// Simulate a web txn
		url, _ := url.Parse("http://localhost:8000")
		r := http.Request{
			Header: http.Header{
				"test": []string{
					name,
				},
			},
			URL:    url,
			Method: http.MethodGet,
		}
		txn.SetWebRequest(WebRequest{
			Header:    r.Header,
			URL:       r.URL,
			Method:    r.Method,
			Transport: TransportHTTP,
			Host:      r.Host,
		})

		// verify that segments and errors work
		s1 := txn.StartSegment(name + "segment")
		txn.NoticeError(errors.New("error" + name))
		s1.End()
		txn.End()

		wg.Done()
	}

	for i := 0; i < threads; i++ {
		go doTxnStuff(app.Application, &wg, fmt.Sprintf("%s-%d", "test", i))
	}
	wg.Wait()
}
```

**Comment by iamemilio** [comment]
Hi @nicoroy2561 Is it possible that your application is also modifying the http object that is stored in the request? I am very certain that we lock our own access to this resource in the go-agent, and can not reproduce this error on my end, but just be cause the agent keeps a lock to resource does't mean that its thread safe, which maps are not. Could you maybe share more details about how your app is making and handling these http requests?

**Comment by nicoroy2561** [comment]
Not my application directly, but I guess the websocket library may be. I am using https://github.com/lesismal/nbio for websocket.

**Comment by iamemilio** [comment]
There is not a lot that we can do here unfortunately. We can not control async access to a resource we do not own, and we are already being as defensive as we can. In go, maps panic when accessed asynchronously to avoid causing memory errors. There needs to be some way to synchronize the access to this http header map in NBIO, otherwise you are better off leaving it alone because you will continue getting these kinds of errors. IMO, you should file an issue against NBIO, or ask in their community about the correct way to access this resource. If you do file an issue, please tag me on it as well.

**Comment by nicoroy2561** [comment]
@iamemilio 
Please help me understand this better: basically the r.Header contains a map that's being accessed concurrently, hence triggering the issue.

Does said r.Header have a mutex for accessing/modifying this map? or is a r.Header inherently unsafe for concurrent use?

**Comment by iamemilio** [comment]
https://github.com/golang/go/blob/6dc7b060cd725aa61421e627ec233e9a936600fc/src/net/http/header.go#L43-L51 ----> https://github.com/golang/go/blob/6dc7b060cd725aa61421e627ec233e9a936600fc/src/net/textproto/header.go#L25


As far as I know, this resource is not thread safe unfortunately

**Comment by nicoroy2561** [comment]
Thank you for the explanation. I think this is unsolvable then - long as there's some other library with concurrent access to the request r.

I think I'll stick with removing the headers for the time being.
Maybe you could add a comment stating that r mustn't be accessed concurrently by other code, and suggest stripping headers if it is.

**Comment by iamemilio** [comment]
Np, if you're able to access the request object safely in some way, a good mitigation strategy could be to make a local copy of it and then pass that copy to the `txn.SetWebRequestHTTP(r)` function. But that is beyond my knowledge. I'll add a note in the docs for this method on our end though.

**Comment by nicoroy2561** [comment]
I agree - making a copy of r would be ideal.
Though I am unsure a copy can be made as easily; r being a struct might need some more workings.

I thought of proposing returning (and altering) a copy of r, but am unsure that would make sense to your userbase.

Either way, thank you for your time and the nice library/service 😁

**Comment by iamemilio** [comment]
🙏 thanks and good luck!
