### ISSUE TITLE
_integrations/nrlogrus/nrlogrus.go should import lowercase "github.com/sirupsen/logrus"

### ISSUE THREAD

**Issue by adminfromhell** [newrelic/go-agent#55]
Currently the `nrlogrus.StandardLogger()` imports `"github.com/Sirupsen/logrus"`. This causes errors inside of existing projects that are already using logrus as described in in their README.

> Seeing weird case-sensitive problems? It's in the past been possible to import Logrus as both upper- and lower-case. Due to the Go package environment, this caused issues in the community and we needed a standard. Some environments experienced problems with the upper-case variant, so the lower-case was decided. Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus. Any package that isn't, should be changed.

There is an open pull request for this already https://github.com/newrelic/go-agent/pull/52

**Comment by robertnewrelic** [comment]
Thanks for pointing it out to us @adminfromhell .  I've replied in the open pull request and have merged the fix to our testing environment.  Expect the fix to be part of our next release!

**Comment by alif** [comment]
Any update on when this will be released? Is the next release coming soon?
Thanks!

**Comment by crenshaw** [comment]
Thanks for your inquiry.  This change is included in our next release which is currently undergoing quality assurance testing. I'm hopeful we'll see something in the coming weeks.

**Comment by crenshaw** [comment]
This fix is available in release 1.10.0, out today.  
See:  https://github.com/newrelic/go-agent/tree/v1.10.0

The CHANGELOG.md describes all the latest updates.  
See: https://source.datanerd.us/go-agent/go-agent/blob/master/CHANGELOG.md
