### ISSUE TITLE
Errors in documentation for code-level metrics

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#550]
https://docs.newrelic.com/docs/apm/agents/go-agent/configuration/go-agent-code-level-metrics-config/
This page mentions a function `newrelic.ConfigCodeLevelMetricsIgnorePrefix` but it is actually [`newrelic.ConfigCodeLevelMetricsIgnoredPrefix`](https://pkg.go.dev/github.com/newrelic/go-agent/v3/newrelic#ConfigCodeLevelMetricsIgnoredPrefix).

https://pkg.go.dev/github.com/newrelic/go-agent/v3/newrelic#CodeLevelMetricsScope
The documentation refers to `SpanCLM` but no such constant exists.

**Comment by nr-swilloughby** [comment]
Corrections made. They still have to go through the editing/release process before appearing. Thanks for the heads up.
