### ISSUE TITLE
Support multiple ignored prefixes for code-level metrics

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#551]
By default code-level metrics will ignore callers with a prefix of `github.com/newrelic/go-agent`. You can customize this via `IgnoredPrefix`  in the `Config` struct, but since it is not a list you cannot have it ignore both prefixes.

Either `IgnoredPrefix` should be deprecated and replaced with a list property, or it should be defined as a comma-separated list of prefixes. `newrelic.ConfigCodeLevelMetricsIgnoredPrefix` will be similarly impacted.

**Comment by nr-swilloughby** [comment]
Thanks for the feature enhancement suggestion. We'll look into that as soon as we can.

**Comment by nr-swilloughby** [comment]
I think the best approach here would be to replace `IgnoredPrefix` with a list property and change `ConfigCodeLevelMetricsIgnoredPrefix` to take a list of strings, preserving its call semantics to be backward compatible (since it can still be called with a single string argument like before).

**Comment by nr-swilloughby** [comment]
Oh, and this also similarly impacts the `WithIgnoredPrefix` option.

**Comment by rittneje** [comment]
@nr-swilloughby Since `IgnoredPrefix` is a public field of `Config`, you cannot replace it without breaking backwards compatibility. You would need two separate fields.

**Comment by nr-swilloughby** [comment]
Yes, that's what I did. `IgnoredPrefix` will be a deprecated field (but still used if set), and the new one is `IgnoredPrefixes` is a slice of strings. `ConfigCodeLevelMetricsIgnoredPrefix` and `WithIgnoredPrefix` can be changed to take a variadic list of strings and still preserve the previous calling syntax, which is backwards compatible unless for some reason someone defines an interface type around those functions, but with those specific functions that seems very unlikely to happen.
