### ISSUE TITLE
GO Newrelic distributed tracing API-> Kafka producer -> Kafka consumer

### ISSUE THREAD

**Issue by JaisimhaSeelam** [newrelic/go-agent#563]
Trying to get newrelic distributed tracing across different microservices implemented in GO

## Description

 Our flow is as below

We first upload a file to a restful API end point, which then does some DB inserts into postgres and pushes a message to a Kafka topic. Then there is another microservice that is consuming the message. So we want to trace this request all the way through. 

For APIs the tracing shows up fine (We are using nrgin middleware to intercept the request). This API now does a Kafka push. After the kafka push we are not able to figure out how to trace the message at the consumer side. Can you brief us on the steps we need to do on the producer and consumer side to see my trace all the way through. 

I tried doing CreateDistributedTracePayload and InsertDistributedTraceHeaders (but this needs to pass Http headers in the input. Wasn't exactly sure why. So i just created a dummy header and set it in there)on producer side. 
On the consumer I tried doing AcceptDistributedTracePayload. But didn't have much luck. 

I tried using the MessageProducerSegment too on the consumer, assuming it would add the necessary trace headers. But with this segment addition I do see a span for that segment in newrelic, but again on consumer side there isn't any activity showing up. 

## Steps to Reproduce

I feel the above process should be good enough. You can skip the db entry. But basically invoke a rest api, that does a kafka publish and then a consumer that listens to the message and processes it. 

## Expected Behavior

Distributed trace should show up all the way from the API to the kafka consumer

## NR Diag results

Not sure

## Your Environment
go version go1.18 darwin/amd64
github.com/newrelic/go-agent v3.18.1
github.com/newrelic/go-agent/v3/integrations/nrgin v1.1.2
My configuration setting for newrelic 
`cfg := newrelic.NewConfig(os.Getenv("NEW_RELIC_APP_NAME"), os.Getenv("NEWRELIC_KEY"))
	cfg.Logger = newrelic.NewDebugLogger(os.Stdout)
	cfg.DistributedTracer.Enabled = true
	cfg.SpanEvents.Enabled = true
	cfg.SpanEvents.Attributes.Include = append(cfg.SpanEvents.Attributes.Include, "buzzLightYear")
	cfg.ErrorCollector.Enabled = true
	cfg.ServerlessMode.Enabled = true`

**Please reach out if you need any more details.**

**Comment by iamemilio** [comment]
Thanks for reporting! As far as I am aware, the go team is currently not sure about the best way to instrument Kafka for distributed tracing, but it is something that is already on our agenda. We will re-asses the priority of this task, and try to get back to you with information as soon as we are able to.

**Comment by JaisimhaSeelam** [comment]
Thank you @iamemilio . Please keep us posted on the progress.

**Comment by JaisimhaSeelam** [comment]
hi @iamemilio, 

Any update on the case? We haven't heard back from you. 

After internal discussion with our team, they do recommend opening a support ticket with newrelic. We do have license with you guys. Do you feel that will help expedite the enhancement/fix? 

Thank you 
Jai

**Comment by iamemilio** [comment]
Sorry for the slow response time. Yes, it would increase the visibility of this issue to our leadership, and may change the prioritization. I think that would be a good idea. To set expectations, we probably can not get to it right away, but if this is a high priority item for your team, then we will definitely try to re-asses the priority accordingly.

**Comment by JaisimhaSeelam** [comment]
Yes its kind of like a high priority item. I will talk to our internal team and get that case opened.

**Comment by JaisimhaSeelam** [comment]
Created a ticket today. https://support.newrelic.com/s/case/5008W00000uAjAdQAK/api-kafka-producer-microservice-kafka-kakfa-consumer-microservice

Hope it will help to expedite the enhancements.

**Comment by Ak-x** [comment]
Hello @JaisimhaSeelam, this is a current roadmap item, and we will provide an update once we have made significant progress here.

**Comment by mirackara** [comment]
Hello @JaisimhaSeelam, we have made significant progress on a kafka integration package. You can follow the changes [here](https://github.com/newrelic/go-agent/pull/706). This integration should resolve your issue. Feel free to open this back up if any issues relating to kafka pop up!
