### ISSUE TITLE
Update Installation For New Relic Golang Agent

### ISSUE THREAD

**Issue by ntcsteve** [newrelic/go-agent#569]
I was going through the docs and guided install for Golang, and saw go get isn’t working as instructed. You need to use go mod init XXX/newrelic, before go get. We should update our docs, and guided install. FYI - https://docs.newrelic.com/docs/apm/agents/go-agent/installation/install-new-relic-go.

**Comment by urvesh-educloud** [comment]
**I am unable to monitor my go project with the new relic**

**I am able to monitor using JAVA**

I have follows the documentation steps: https://docs.newrelic.com/docs/apm/agents/go-agent/installation/install-new-relic-go/

1. **From [github.com/newrelic/go-agent](https://github.com/newrelic/go-agent), use your preferred process; for example:**
    bash command `go get github.com/newrelic/go-agent/v3/newrelic`

2. **Import the github.com/newrelic/go-agent/v3/newrelic package in your application.**
   `  import github.com/newrelic/go-agent/v3/newrelic`

3. **Initialize the Go agent by adding the following in the main function or in an init block:**
      ```
      app, err := newrelic.NewApplication(
          newrelic.ConfigAppName("Your Application Name"),
          newrelic.ConfigLicense("YOUR_NEW_RELIC_LICENSE_KEY")
      )
      ```

**NOTE: I have follows all the trouble shooting as well.**

**main.go**
```
package main

import (
	"fmt"
	"io"
	"net/http"

	"github.com/newrelic/go-agent/v3/newrelic"
)

var newrelicApp *newrelic.Application

func main() {
	app, err := newrelic.NewApplication(
		newrelic.ConfigAppName("MyAppMain"),
		newrelic.ConfigLicense("280d644a5b4fc4859d5fa75b8897f4422bb5NRAL"),
		newrelic.ConfigAppLogForwardingEnabled(true),
	)
	if err != nil {
		fmt.Printf("error is " + err.Error())
	} else {
		newrelicApp = app
		http.HandleFunc(newrelic.WrapHandleFunc(app, "/test", customEvent))
	}
}

func customEvent(w http.ResponseWriter, req *http.Request) {
	io.WriteString(w, "recording a custom event")

	newrelicApp.RecordCustomEvent("MyAppMainEvent", map[string]interface{}{
		"text":      "Hello VP",
		"env":       "go_local",
		"alertType": "error",
		"priority":  "Critical",
		"source":    "MyAppMain",
	})
}
```

**Comment by iamemilio** [comment]
@urvesh-educloud Your license Key associated with this account was posted here and is compromised. Please rotate it in New Relic One.
