### ISSUE TITLE
How to skip specific errors while logging to newrelic

### ISSUE THREAD

**Issue by dineshkumar-cse** [newrelic/go-agent#58]
while using `newrelic.Transaction` as `http.ResponseWriter`, the status code errors are shown in newrelic Error Analytics and Errors, how could we skip specific status codes?

I'm concerned about this because this error rate affects the Appdex Score, and can't have alerts on Appdex Low or specific to status codes.

**Comment by robertnewrelic** [comment]
Hey @dineshkumar-cse !  You can ignore specific status codes by setting `IgnoreStatusCodes` in the `ErrorCollector` struct.  See: https://github.com/newrelic/go-agent/blob/master/config.go#L74-L78

If you have additional questions I recommend our [support site](http://support.newrelic.com/) and [community forum](http://forum.newrelic.com/) as great resources to help.  Going forward we will be focusing our efforts to help the community via those outlets and I want to make sure we get back to everyone as timely as we can :)

**Comment by robertnewrelic** [comment]
Closing issue as resolved!  Let me know if that's not the case :)
