### ISSUE TITLE
New relic integration with go : I am unable to monitor my go project with new relic 

### ISSUE THREAD

**Issue by urvesh-educloud** [newrelic/go-agent#585]
**I am unable to monitor my go project with the new relic**

**I am able to monitor using JAVA**

I have follows the documentation steps: https://docs.newrelic.com/docs/apm/agents/go-agent/installation/install-new-relic-go/

1. **From [github.com/newrelic/go-agent](https://github.com/newrelic/go-agent), use your preferred process; for example:**
    bash command `go get github.com/newrelic/go-agent/v3/newrelic`

2. **Import the github.com/newrelic/go-agent/v3/newrelic package in your application.**
   `  import github.com/newrelic/go-agent/v3/newrelic`

3. **Initialize the Go agent by adding the following in the main function or in an init block:**
      ```
      app, err := newrelic.NewApplication(
          newrelic.ConfigAppName("Your Application Name"),
          newrelic.ConfigLicense("YOUR_NEW_RELIC_LICENSE_KEY")
      )
      ```

**NOTE: I have follows all the trouble shooting as well.**

**main.go**
```
package main

import (
	"fmt"
	"io"
	"net/http"

	"github.com/newrelic/go-agent/v3/newrelic"
)

var newrelicApp *newrelic.Application

func main() {
	app, err := newrelic.NewApplication(
		newrelic.ConfigAppName("MyAppMain"),
		newrelic.ConfigLicense("YOUR_NEW_RELIC_LICENSE_KEY"),
		newrelic.ConfigAppLogForwardingEnabled(true),
	)
	if err != nil {
		fmt.Printf("error is " + err.Error())
	} else {
		newrelicApp = app
		http.HandleFunc(newrelic.WrapHandleFunc(app, "/test", customEvent))
	}
}

func customEvent(w http.ResponseWriter, req *http.Request) {
	io.WriteString(w, "recording a custom event")

	newrelicApp.RecordCustomEvent("MyAppMainEvent", map[string]interface{}{
		"text":      "Hello VP",
		"env":       "go_local",
		"alertType": "error",
		"priority":  "Critical",
		"source":    "MyAppMain",
	})
}
```

**Comment by iamemilio** [comment]
Take a look at this example code and just double check that your implementation is following best practices: https://github.com/newrelic/go-agent/blob/master/v3/examples/server/main.go

If you're still having trouble let us know

**Comment by urvesh-educloud** [comment]
Hi @iamemilio,
How can I execute this?
Can you provide the example so I can refer?

**Comment by iamemilio** [comment]
package main

import (
	"errors"
	"fmt"
	"io"
	"math/rand"
	"net/http"
	"os"
	"sync"
	"time"

	"github.com/newrelic/go-agent/v3/newrelic"
)

func customEvent(w http.ResponseWriter, r *http.Request) {
	txn := newrelic.FromContext(r.Context())

	io.WriteString(w, "recording a custom event")

	txn.Application().RecordCustomEvent("MyAppMainEvent", map[string]interface{}{
		"text":      "Hello VP",
		"env":       "go_local",
		"alertType": "error",
		"priority":  "Critical",
		"source":    "MyAppMain",
	})
}

func main() {
	app, err := newrelic.NewApplication(
		newrelic.ConfigAppName("MyAppMain"),
		newrelic.ConfigLicense("YOUR_NEW_RELIC_LICENSE_KEY"),
		newrelic.ConfigAppLogForwardingEnabled(true),
	)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	
	http.HandleFunc(newrelic.WrapHandleFunc(app, "/custom_event", customEvent))
	http.ListenAndServe(":8000", nil)
}

**Comment by iamemilio** [comment]
hi @urvesh-educloud I am going to close this and assume that the solution provided worked for you. If that is not the case, please re-open the ticket
