### ISSUE TITLE
Set SegmentStartTime to time in the past

### ISSUE THREAD

**Issue by duhruh** [newrelic/go-agent#59]
Can we make it possible to set SegmentStartTime to a specific time in the past.

Use case:

currently in one of my projects I use an ORM called [Upperio](https://upper.io/db.v3/). In this ORM and most they give you the ability to [add a query logger](https://godoc.org/upper.io/db.v3#Logger). This query logger has in it all the information I would need to pass to `newrelic.DatastoreSegment` (context, start time, end time, query string). This is problematic when trying to implement this logger with newrelic as right now it seems you guys require me to run

```
// 	defer newrelic.DatastoreSegment{
// 		StartTime:  newrelic.StartSegmentNow(txn),
// 		Product:    newrelic.DatastoreMySQL,
// 		Collection: "my_table",
// 		Operation:  "SELECT",
// 	}.End()
```

before any query call. I would like to not flood my code base with these calls if they can be in one place. 

Do you guys have any suggestions on how i should do this? Does the newrelic client already provide me with a way to generate a StartTime that i'm just missing?

**Comment by crenshaw** [comment]
Thanks for getting in touch! We're in the process of closing the issues section of the Go agent repository in favor of our support channels.  We want to ensure that all issues and suggestions get dealt with in a more timely manner.

Please reach out to us on our [support site](https://support.newrelic.com/) or our [community forum](https://discuss.newrelic.com/) and we'll be happy to help you.
