### ISSUE TITLE
Distributed Tracer Reservoir Limit Not Being Used

### ISSUE THREAD

**Issue by tsmith-rv** [newrelic/go-agent#600]
Instead of the configurable distributed tracer reservoir limit, the `defaultMaxSpanEvents` is being used to determine whether or not to save a span event.

## Description

https://github.com/newrelic/go-agent/blob/38d939bb231d1e771975abe7afe71ed4212cd99b/v3/newrelic/tracing.go#L402

When adding spans to a transaction, after you have added 2000 spans you are no longer able to add anymore, despite setting a higher reservoir limit using `newrelic.ConfigDistributedTracerReservoirLimit()`. This is because the `defaultMaxSpanEvents` constant is being used in the check, which is set at 2000. There is a note in the code expressing the need to replace this functionality.

https://github.com/newrelic/go-agent/blob/38d939bb231d1e771975abe7afe71ed4212cd99b/v3/newrelic/limits.go#L41

## Steps to Reproduce

Try to add more than 2000 spans to a transaction.

## Expected Behavior

I would expect to see all the spans I instrumented in the code, up to the number I passed in to `newrelic.ConfigDistributedTracerReservoirLimit()`.

**Comment by Ak-x** [comment]
Hello @tsmith-rv can you confirm this is still an issue on the latest Go Agent, if so please re-open this issue.

**Comment by tsmith-rv** [comment]
This does still seem to be an issue in the latest agent `v3.20.3`:

https://github.com/newrelic/go-agent/blob/dd6e323446a7aff70e700be2bfae97bf899805b0/v3/newrelic/tracing.go#L416

https://github.com/newrelic/go-agent/blob/dd6e323446a7aff70e700be2bfae97bf899805b0/v3/newrelic/limits.go#L41
