### ISSUE TITLE
Compression Memory Leak

### ISSUE THREAD

**Issue by mhmtszr** [newrelic/go-agent#619]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
We have been observing the memory increase in our Go applications for a long time. When We look at the cumulative increase of the memories used by the application with the memory dump method, We observed that the New Relic agent uses a lot of memory while **doing gzip compression.**

## Versions
github.com/newrelic/go-agent/v3 v3.20.1
github.com/newrelic/go-agent/v3/integrations/nrgin v1.1.3

## Example memory dump
![image](https://user-images.githubusercontent.com/35079195/210282500-cf7fbbf9-3fe9-4047-a9c3-615d08f72c96.png)

## Details
Instead of creating a new gzip writer for every collect request, use common ones by using gzip writer [sync pool](https://pkg.go.dev/sync#Pool).

**Comment by iamemilio** [comment]
This is great to see, thanks for filing this and a pull request with us! There are a lot of old bits and pieces in the code, and it can be hard for us to spot issues like this. I am not sure I would characterize this as a memory leak from the data you posted, it looks like it's fairly fixed. I would love to see what the memory consumption stats look like with the PR you proposed too.

**Comment by mhmtszr** [comment]
@iamemilio I tested with my PR, and I am sharing the results with you. I only changed the New Relic Go Agent, and now the memory increase decreased by 22%, at the same time, the CPU usage has a noticeable decrease.

**Comment by Ak-x** [comment]
This fix will be included in an upcoming release

**Comment by mhmtszr** [comment]
Fixed with 3.20.3.
