### ISSUE TITLE
Delete old v2 code

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#639]
Considering what happened in #636, and the fact that v2 is now [completed unsupported](https://docs.newrelic.com/docs/apm/agents/go-agent/get-started/go-agent-eol-policy/), all the old v2 code should be deleted to avoid confusion.

That is:
1. all the .go files at the root of the repo
2. the [_integrations](https://github.com/newrelic/go-agent/tree/master/_integrations) folder
3. the [examples](https://github.com/newrelic/go-agent/tree/master/examples) folder
4. the [internal](https://github.com/newrelic/go-agent/tree/master/internal) folder

**Comment by nr-swilloughby** [comment]
Agreed, this is already on our roadmap to do.
