### ISSUE TITLE
Skip fetching location if CLM is disabled

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#640]
## Summary

Currently the implementation of `newrelic.WrapHandle` avoids fetching the caller's location for CLM if CLM is disabled (either for the whole app or just the one transaction). However, there is no way for any package clients to emulate this behavior, because they do not have any way to tell if CLM will be enabled.

## Desired Behavior

There needs to be a way to avoid pointless location lookups even when I cannot use `newrelic.WrapHandle`.

## Possible Solution

It would be a lot simpler if `LocationOverride` were deprecated and replaced with a `func() *CodeLocation`. Then the `TraceOption` itself would not have to do any checks. Instead, `newTxn` would first determine if CLM was enabled, and only invoke the callback if it was. I believe this would also remove the need for custom code in `newrelic.WrapHandle`.

**Comment by nr-swilloughby** [comment]
I agree with the proposed solution; looking at what this would entail to get done quickly.

**Comment by nr-swilloughby** [comment]
looking at this again, sorry for the delay

**Comment by nr-swilloughby** [comment]
This will be going out in a release soon

**Comment by nr-swilloughby** [comment]
Implemented in 3.29.0.
