### ISSUE TITLE
Distributed Tracer Reservoir Limit Not Being Used

### ISSUE THREAD

**Issue by tsmith-rv** [newrelic/go-agent#643]
Reopened #600 as instructed since the latest Go Agent (`v3.20.3`) still has this issue:

Instead of the configurable distributed tracer reservoir limit, the `defaultMaxSpanEvents` is being used to determine whether or not to save a span event.

## Description

https://github.com/newrelic/go-agent/blob/dd6e323446a7aff70e700be2bfae97bf899805b0/v3/newrelic/tracing.go#L416

When adding spans to a transaction, after you have added 2000 spans you are no longer able to add anymore, despite setting a higher reservoir limit using `newrelic.ConfigDistributedTracerReservoirLimit()`. This is because the `defaultMaxSpanEvents` constant is being used in the check, which is set at 2000. There is a note in the code expressing the need to replace this functionality.

https://github.com/newrelic/go-agent/blob/dd6e323446a7aff70e700be2bfae97bf899805b0/v3/newrelic/limits.go#L41

## Steps to Reproduce

Try to add more than 2000 spans to a transaction.

## Expected Behavior

I would expect to see all the spans I instrumented in the code, up to the number I passed in to `newrelic.ConfigDistributedTracerReservoirLimit()`.

**Comment by iamemilio** [comment]
A fix for this should be included in the 3.20.4 release.
