### ISSUE TITLE
txn pass with context not work

### ISSUE THREAD

**Issue by sergeylanzman** [newrelic/go-agent#7]
I have problems with new API. In version 0.6.1 this work. 
I need pass txn with context in other functions.
newrelic.wrap this private struct and not have StartSegmentNow

```
txn := App.StartTransaction("task 1:", nil, nil)
ctx := context.WithValue(context.Background(), "txn", txn)
datafrom_redis :=  getFromList("test", ctx)

func getFromList(name string,ctx context.Context){
  content := ctx.Value("txn")
  txn := content.(newrelic.Transaction) 
  defer newrelic.DatastoreSegment{
			StartTime:  newrelic.StartSegmentNow(txn),
			Product:    newrelic.DatastoreRedis,
			Collection: "my_table",
			Operation:  "select",
  }.End()
}
```

```
panic: interface conversion: newrelic.wrap is not newrelic.Transaction: missing method StartSegmentNow
```

**Comment by willnewrelic** [comment]
Hi sergeylanzman

I am unable to reproduce your problem.  I tested your code snippet successfully for Go 1.3, 1.5, and 1.6.

What version of Go are you using?  Could you please provide a complete reproduction program?

**Comment by sergeylanzman** [comment]
my bad with version in vendor folder and gopath, this work. Sorry
