### ISSUE TITLE
add getter for transaction name

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#714]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Add a `Name() string` method to `Transaction`.

## Desired Behavior

It should return the transaction name, as passed to `StartTransaction` or `SetName`.

## Additional context

We'd like to be able to easily include the transaction name in the attributes for `RecordCustomEvent`. However, there doesn't seem to be a way to do this without keeping track of the name ourselves.

Alternatively, it would much nicer if there were a way to do `RecordCustomEvent` within a transaction.

**Comment by nr-swilloughby** [comment]
released
