### ISSUE TITLE
github.com/golang/protobuf is deprecated

### ISSUE THREAD

**Issue by panapol-p** [newrelic/go-agent#777]
github.com/golang/protobuf is deprecated

## Description
we should use google.golang.org/protobuf instead of github.com/golang/protobuf

_It has been superseded by the [google.golang.org/protobuf](https://pkg.go.dev/mod/google.golang.org/protobuf) module, which contains an updated and simplified API, support for protobuf reflection, and many other improvements. We recommend that new code use the google.golang.org/protobuf module._

**Comment by iamemilio** [comment]
This has been fixed in more recent versions of the go agent. Thanks for reporting.
