### ISSUE TITLE
Support windows build

### ISSUE THREAD

**Issue by ianomad** [newrelic/go-agent#8]
Are you guys planning to support it for windows?
Right now I can't even separate out handlers_windows/linux, because go get doesn't work.
Can you at least add implementation functions for windows so that it would complain on run time, but would still compile.

**Comment by gambrell** [comment]
Attempting to cross compile on Mac to Windows with env GOOS=windows GOARCH=amd64 go build -v

```
github.com/newrelic/go-agent/internal
github.com/newrelic/go-agent/internal/utilization
# github.com/newrelic/go-agent/internal/utilization
../../github.com/newrelic/go-agent/internal/utilization/utilization.go:127: undefined: sysinfo.PhysicalMemoryBytes
# github.com/newrelic/go-agent/internal
../../github.com/newrelic/go-agent/internal/sampler.go:38: undefined: syscall.Getrusage
../../github.com/newrelic/go-agent/internal/sampler.go:38: undefined: syscall.RUSAGE_SELF
../../github.com/newrelic/go-agent/internal/sampler.go:40: ru.Utime undefined (type syscall.Rusage has no field or method Utime)
../../github.com/newrelic/go-agent/internal/sampler.go:41: ru.Stime undefined (type syscall.Rusage has no field or method Time)

make: *** [windows] Error 2
```

**Comment by panzerdev** [comment]
This dependency shouldn't break building on Windows. Go's strong point is to be agnostic so why break this?

**Comment by willnewrelic** [comment]
Hi
We're planning support for additional operating systems, including Windows.  Until then, we'll label this "roadmap" to reflect that it's under consideration.

**Comment by nathany** [comment]
FYI: A few Go projects (such as [caddy](https://github.com/mholt/caddy) and [fsnotify](https://github.com/fsnotify/fsnotify)) use [AppVeyor](https://www.appveyor.com/) for CI to ensure that the Windows build keeps on working.

**Comment by willnewrelic** [comment]
Hi All

Version 1.5.0 was just released with Windows support added.  Thanks for your help @ianomad !
