### ISSUE TITLE
Is there a method to monitor websocket?

### ISSUE THREAD

**Issue by ytkang** [newrelic/go-agent#80]
I'm developing a server using [gorilla websocket](https://github.com/gorilla/websocket)
Can I monitor websocket by using this newrelic library?

**Comment by willnewrelic** [comment]
Hi @ytkang 

This library does not have instrumentation specific to gorilla websocket.  Nonetheless, you can use this library to monitor your application:  The API is designed to be flexible enough to instrument anything.

If you post a snippet example of how you are using gorilla websocket I would be happy to provide instrumentation direction.

**Comment by ytkang** [comment]
@willnewrelic 
I used StartTransaction function for each request.
This is an example.

	func readPump() {
		for {
			err := ReadLine(Conn)
			if err != nil {
				break
			}
		}
	}

	func ReadLine(conn *websocket.Conn) (err error) {
		var r io.Reader
		err = nil
		_, r, err = conn.NextReader()
		if err != nil {
			fmt.Println("reader error ", err.Error())
			return err
		}
		nr := bufio.NewReader(r)
		for err == nil {
			message, readErr := nr.ReadSlice('\n')

			err = readErr
			if message != nil {
				processMessage(message)
			}
		}

		if err == io.EOF {
			err = nil
		}

		return err
	}

	func processMessage(message []byte) {
		req := Request{}
		err := req.UnmarshalJSON(message)

		if err == nil {
			var txn newrelic.Transaction = nil

			if NewRelicApp != nil {
				txn = NewRelicApp.StartTransaction(req.Path, nil, nil)
				defer txn.End()
			}

			f := getHandler(req.Path)
			if f != nil{
				f(req.Path, message, c, txn)
			}
		}
	}

**Comment by willnewrelic** [comment]
Hi @ytkang 

That code looks reasonable to me!  You might want to create the transaction in the `readPump` for loop so that you can time all the time spent in `ReadLine`.

If you have more questions about instrumentation, please don't hesitate to open a support ticket.

**Comment by ytkang** [comment]
@willnewrelic yes, you're right. but I needed to check time for each line. It will be case by case.
