### ISSUE TITLE
Go Modules Support

### ISSUE THREAD

**Issue by codyolsen** [newrelic/go-agent#81]
Hello! Any future plans for adding [module support](https://github.com/golang/go/wiki/Modules#gomod)?

**Comment by willnewrelic** [comment]
Hi @codyolsen 

We are eager to conform to community standards regarding versioning.  So, yes, I expect us to adopt module support!  I must admit, we haven't been following the proposal closely.  Do you have any specific advice or things we should be aware of?

**Comment by codyolsen** [comment]
Hey @willnewrelic. It's actually really simple to add module support. [You just run `go mod init` in your package and then build to list dependencies in the go.mod/go.sum file.](https://github.com/golang/go/wiki/Modules#how-to-define-a-module) However, based on the fork I made it looks like you don't have any external dependencies in this package... which is amazing 👍.

The one caveat that you might run into: Any package past v2 has some specific instructions for how to release the new module version: [Golang: releasing-modules-v2-or-higher](releasing-modules-v2-or-higher) Based on the conventions you'd have to make your modules release v3.

If there are no concerns about making a v3 release then it should be an easy update!

**Comment by willnewrelic** [comment]
Hi @codyolsen !

I've asked a question about semantic versioning here:  https://github.com/newrelic/go-agent/issues/83

I would love your feedback!

**Comment by codyolsen** [comment]
@willnewrelic I'm not currently using the go-agent in anything mission critical, so I think my input would fall second priority to users with current application dependencies.

**Comment by purple4reina** [comment]
@codyolsen We just released v3.0.0 of the Go Agent with Go Modules support! Take a look and let us know what you think!
