### ISSUE TITLE
proposal: Add Transaction.RecordCustomEvent

### ISSUE THREAD

**Issue by abuchanan-nr** [newrelic/go-agent#82]
Is it possible to add RecordCustomEvent and RecordCustomMetric to the Transaction interface?

We pass transaction throughout a lot of our code. When we want to record custom events or metrics, we also need to thread the Application type through the code too. It definitely adds a lot of verbosity to our code, and again, these are passed deep into our code.

If the internal transaction type is already carrying around the necessary app data, it might be easy to add these methods to the transaction type.

**Comment by willnewrelic** [comment]
We have just released version 2.4.0 with a `Transaction.Application` method!
