### ISSUE TITLE
transaction.go reqBody(req *http.Request) turn nil body into non Nil body for request.Body == http.NoBody

### ISSUE THREAD

**Issue by milhoan** [newrelic/go-agent#822]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
We use gorilla middleware, which calls `txn.SetWebRequestHTTP(r)`, which calls 

https://github.com/newrelic/go-agent/blob/0e521dc894ec887e31125067f28bd3992cf33310/v3/newrelic/transaction.go#L221

This function causes nil request.Body to be set to non nil request.Body, but with zero length.  When our handler function receives the request later, it breaks.

Create mux with a handler function after setting the nrgorilla middleware on the mux
Make a request using http.NoBody as the request.Body payload, then access the request.Body inside the handler function.

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

request.Body of type http.NoBody should remain nil or set to http.NoBody.  it should have have empty zero length io.Reader created and set on it.  Doing so breaks http handlers that check for nil / http.NoBody

## NR Diag results

[NOTE]: # ( Provide any other relevant log data. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Reproduction case

[TIP]: # ( Link a sample application that demonstrates the issue. )

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by nr-swilloughby** [comment]
Fixed in PR 824
