### ISSUE TITLE
Versioning Question

### ISSUE THREAD

**Issue by willnewrelic** [newrelic/go-agent#83]
Hi All!

We have a question for you about versioning!

As we add new features, we have been adding new methods to the `Application` and `Transaction` interface types.  For example, in the latest release we introduced an `Transaction.Application` method.  We have not been increasing the major version number when these interfaces change. Although there is no formal specification about what constitutes a breaking change, many view new interface methods to be breaking since other implementations of these interfaces need the new methods.  In light of Go Module support, we are thinking more about this problem and when we should increase the major version number. Possible paths forward:

* Keep introducing new methods to the `Application` and `Transaction` types and increment the major version number.  Using modules, lots of major versions could be painful.

* Avoid introducing new methods by implementing new functionality as functions. eg.  `Transaction.Application()` method could have been `newrelic.GetApplication(txn Transaction)`. This has the downside that auto-complete is less useful and it's harder to see what you can do with an `Application` or a `Transaction`.

* Make a big breaking change release where we turn the `Application` and `Transaction` types into structs with pointer receiver methods.  This has the downside that people who are passing around the transaction around their functions would need to change all their parameters from `txn newrelic.Transaction` to `txn *newrelic.Transaction`.

* Keep adding methods to the `Transaction` and `Application` interfaces as minor version changes. 
 The pain caused by adding new methods could be minimized by introducing `StubTransaction` and `StubApplication` structs which consumers could embed into their own `Transaction` and `Application` implementations.

What do you think?

**Comment by v3n** [comment]
So ultimately, this boils down to the Go paradigm, "accept interfaces, return structs".

I think it's extremely valuable for go-agent to receive Transaction interfaces, it allows me to do injection-based testing or wrap the underlying transaction struct to extend the functionality.

The methods that the internal library uses on a transaction (things like `SetWebRequest()` et al) should be on the interface. User-land helper methods (like `Application()` should be on the struct). For the most part, this lets you maintain compatibility (though I would definitely suggest a big interface refactor before going to v3, so you present a minimally implemented interface).

This is similar to option 3, but is a much heavier refactor, but it allows you to maintain compatibility in the future. (an example of this might be net/http's `RoundTripper` vs. `Transport`).

You could also just not use go modules and just stay an incompatible package.

I definitely think major version bumps every time is a huge no-go though.
