### ISSUE TITLE
UNKNOWN log levels when using the native log package

### ISSUE THREAD

**Issue by hammady** [newrelic/go-agent#842]
## Summary

Go native log package does not support log levels. However, starting from go 1.21, a new standard package was introduced: [log/slog](https://pkg.go.dev/log/slog) which supports structured logging as well as log levels. I was able to integrate the go agent with slog to report logs in context. However, because log levels happen outside the Newrelic `logWriter`, records are all reported without the `Severity` attribute and hence show as `UNKNOWN` in the APM UI.

<img width="446" alt="image" src="https://github.com/newrelic/go-agent/assets/855847/34b37900-b5f0-4469-a9e3-b2081953547f">

## Desired Behaviour

I would like the go agent to be able to be integrated deeper with slog so that the correct severity (level) is reported with each record.

Example from the ruby agent:

<img width="442" alt="image" src="https://github.com/newrelic/go-agent/assets/855847/bb457d41-917d-4693-8333-8792ae2614e3">

## Additional context

Showing log severity within APM UI is useful in observability like all other agents, nothing specific here. It is only missing because it was not supported in the standard `log` package before, but now it is supported through `log/slog`

Note: Here is how I did the integration with slog:

```go
writer := logWriter.New(os.Stdout, app)
options := slog.HandlerOptions{
	Level: utils.GetLogLevel(),
}
logger := slog.New(slog.NewTextHandler(writer, &options))
// set default logger for top-level functions like log.Println(), log.Printf(), etc.
slog.SetDefault(logger)
```

**Comment by iamemilio** [comment]
Please take a look at the new nrslog package!

**Comment by hammady** [comment]
@iamemilio thanks for the follow-up. I can see nrslog has been added just 3 weeks ago, great job!
I had to switch to Logrus to get the complete functionality of structured logging + NR context.
