### ISSUE TITLE
Feature request: Agent stats

### ISSUE THREAD

**Issue by gaillard** [newrelic/go-agent#85]
It would be very useful if a couple of stats could be tracked and fetched from the agent pkg.
The main one I am interested in at the moment is bandwidth usage.

**Comment by willnewrelic** [comment]
Hi @gaillard 

Are you interested in the agent's bandwidth usage, or all bandwidth usage?

**Comment by gaillard** [comment]
Just the agent, plenty of other tools for the system as a whole such as the counters linux stack maintains for that.

**Comment by willnewrelic** [comment]
Hi @gaillard 

The [Config](https://godoc.org/github.com/newrelic/go-agent#Config) has a `Transport` field that you can use to inspect all agent network traffic.  Here is an example of using it to record the number of agent bytes sent:

https://gist.github.com/willnewrelic/96b7864d120b96a1c6218d1d780a7b8a

**Comment by gaillard** [comment]
@willnewrelic I can certainly do that and would feed it back into the agent as a tx. But what would be really great is if we could get request/response size added to metrics for all ExternalSegments automatically, just like it already does for timing. This is similar to the other metrics that happen for DatastoreSegments already. Then the agent could simply add an ExternalSegment for its own roundtrip.

**Comment by willnewrelic** [comment]
Hi @gaillard 

I have recorded this request in our feature request system.  Adding request/response size to ExternalSegments would certainly be useful.  I'm going to close this, but I will notify you if this functionality is released.  We appreciate this idea.
