### ISSUE TITLE
Changelog Go agent EOL Policy link is broken

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#856]
https://github.com/newrelic/go-agent/blob/master/CHANGELOG.md

Under "Support statement" for each release, it has a link for [Go agent EOL Policy](https://github.com/newrelic/go-agent/blob/master/docs/apm/agents/go-agent/get-started/go-agent-eol-policy). However, this link is broken.

![image](https://github.com/newrelic/go-agent/assets/28784688/407e727d-8651-4c42-9fd6-9d829302fbbf)

The correct link is https://docs.newrelic.com/docs/apm/agents/go-agent/get-started/go-agent-eol-policy/

**Comment by iamemilio** [comment]
thanks 😆 . We will fix that!
