### ISSUE TITLE
zap logger.With log message properties are not sent to new relic

### ISSUE THREAD

**Issue by yehudamakarov** [newrelic/go-agent#867]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Regarding the zap integration for the go agent,
- i make a background logger as described in the docs. 
- when I make new loggers from it with `logger.With("<prop name>", "<prop value>")` although the properties are visible in the log's json on the console, those properties are not in new relic.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
See above.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
Any properties added to json structured log messages should be in the new relic log message.

## NR Diag results

[NOTE]: # ( Provide any other relevant log data. )
can't run that in google cloud run, sorry.
## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )
- google cloud run
- i previously opened #859

**Comment by yehudamakarov** [comment]
i opened a support case [here](https://onenr.io/0dQeoJ2ddRe)

**Comment by iamemilio** [comment]
we dont support attributes yet unfortunately, its on our roadmap

**Comment by iamemilio** [comment]
this is for all logging products in go

**Comment by yehudamakarov** [comment]
aye. ok.

I wish i saw this in the docs (wondering if i missed it, or it can be added)

thank you! (this is a key feature for me 🤔)

**Comment by stefanoschrs** [comment]
@iamemilio do we have an estimation on when is this feature going to be added?
