### ISSUE TITLE
413 payload too large

### ISSUE THREAD

**Issue by gaillard** [newrelic/go-agent#89]
I have a support ticket open (353273) but perhaps there is a faster answer here? :D I am wondering what actual number is the limit in order to hit that 413? Also what is it based on, the total request body size compressed?

**Comment by willnewrelic** [comment]
Hey @gaillard 

It appears that you were hitting that 413 limit due to a large number of external metrics, and that the problem has been fixed?  Message us in support ticket if you're still experiencing issues.

**Comment by gaillard** [comment]
It ended up being just an increased size due to some hashes we had added to the tx attributes (not metrics), which can't compress well of course since they are all unique so must have contributed to the size a lot.
It would still be very helpful to know the size limit. It looks to be ~1MB of body size for the tx events?

**Comment by willnewrelic** [comment]
@gaillard  Yes, I believe that the limit if 1MB currently.
