### ISSUE TITLE
Gin Framework support

### ISSUE THREAD

**Issue by johnzeng** [newrelic/go-agent#9]
Do you guys have a plan to support gin-go?
Or, do you have any idea can make it possible to allow me to build one by myself?

**Comment by bbrodriges** [comment]
Well, you can add newrelic to gin fairly easy:
```go
func NewrelicMiddleware(appName string, key string) gin.HandlerFunc {

	if appName == "" || key == "" {
		return func(c *gin.Context) {}
	}

	config := newrelic.NewConfig(appName, key)
	app, err := newrelic.NewApplication(config)

	if err != nil {
                panic(err)
        }

	return func(c *gin.Context) {
		txn := app.StartTransaction(c.Request.URL.Path, c.Writer, c.Request)
		defer txn.End()
		c.Next()
	}
}
```

**Comment by johnzeng** [comment]
@bbrodriges I have tried this but it's not getting the errors from my response, so I think this is not good enough for me. I think a better way is put the txn into the gin.Context so I can make more segment and set error for it.

**Comment by bbrodriges** [comment]
@johnzeng totally agree with you. I have wrote a small wrapper to log errors with new relic transaction in gin context:

```go
// WrapError records error using New Relic transaction
// and returns err back to caller function.
// Example:
//    myint, err := strconv.Atoi("golang")
//    if newrelic.WrapError(c, err) != nil {
//       panic(err)
//    }
func WrapError(c *gin.Context, err error) error {
	if err != nil {
		if txn, ok := c.Get("nrtxn"); ok {
			if nrtxn, ok := txn.(newrelic.Transaction); ok {
				nrtxn.NoticeError(err)
			}
		}
	}

	return err
}
```

**Comment by willnewrelic** [comment]
Hi All,

Proposed Gin support available here:  https://github.com/newrelic/go-agent/pull/28

Give it a try!  We are eager to get your feedback.
