### ISSUE TITLE
Empty httpResponseStatus with Nrgin

### ISSUE THREAD

**Issue by paulogustavosouza** [newrelic/go-agent#90]
Hi guys, how are you?

So, I'm trying using new relic agent with gin and I'm using your nrgin adapter but something wrong are happing.

The http status code is always empty when I just send an empty response.

<img width="728" alt="Captura de Tela 2019-05-31 às 18 42 30" src="https://user-images.githubusercontent.com/45035491/58736409-14654f80-83d4-11e9-9a84-990bf6324141.png">

Why do you don't set the http status code when `WriteHeader` is called ?

Look this [code](https://github.com/newrelic/go-agent/blob/master/_integrations/nrgin/v1/nrgin.go): 

```go
func (w *replacementResponseWriter) WriteHeader(code int) {
	w.code = code
	w.ResponseWriter.WriteHeader(code)
}
```

So if I wanna an empty response body with some status code new relic doesn't will save the status code because gin just call `WriteHeader`:

> Code: https://github.com/gin-gonic/gin/blob/master/context.go
> Line: 730
> 

```go
// Status sets the HTTP response code.
func (c *Context) Status(code int) {
	c.writermem.WriteHeader(code)
}
```

What we can do about it ?

**Comment by willnewrelic** [comment]
Hi @paulogustavosouza !

I've opened a PR fix against Gin here:  https://github.com/gin-gonic/gin/pull/1606  Perhaps you could encourage them to merge it too!  =D

**Comment by paulogustavosouza** [comment]
Heeyyy, since gin guys already merged the issue gin-gonic/gin#1606, will you work in this issue?

**Comment by purple4reina** [comment]
Hey @paulogustavosouza,

Thanks for the ping! I've confirmed that https://github.com/gin-gonic/gin/pull/1606 allows users to capture the status code when a response body is written. I've also confirmed your issue here, that when just setting the status (and not response body) you are not seeing the status code.

I'll go ahead and take a look now at what it will take to get this fixed for you. I'll keep you up to date with what I find.

For reference, I'm using this handler for testing:

```go
func handler(c *gin.Context) {
    c.Status(500)
}
```

**Comment by purple4reina** [comment]
Hello again @paulogustavosouza,

We have tracked down the issue of the missing response status codes. The fix will be released with the next version of the agent. Thanks so much for bringing this to our attention!

I'm going to close this issue, but if you have any questions or concerns, please go ahead and reopen it. We're always happy to help.
