### ISSUE TITLE
potential bug in newAppRun

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#918]
I came across the following code while trying to diagnose an oddity we are seeing with "expected status codes".

https://github.com/newrelic/go-agent/blob/424d17590487f6633a2edd5fc272737e46355900/v3/newrelic/app_run.go#L102-L108

Should that instead say `run.Config.ErrorCollector.ExpectStatusCodes != nil`?

**Comment by iamemilio** [comment]
Seems like a likely bug, we will make a ticked for it and fix this.

**Comment by mirackara** [comment]
Released fix with #924. Closing this out for now!
