### ISSUE TITLE
undefined: mysql.NewConnector

### ISSUE THREAD

**Issue by wayneashleyberry** [newrelic/go-agent#92]
```
../../../../go/pkg/mod/github.com/newrelic/go-agent@v2.8.0+incompatible/_integrations/nrmysql/nrmysql.go:79:20: undefined: mysql.NewConnector
```

I've started implementing the new MySQL client added in [`v2.8.0`](https://github.com/newrelic/go-agent/blob/master/CHANGELOG.md#280) and immediately get a compiler error.

It's worth noting here that I am using [jmoiron/sqlx](https://github.com/jmoiron/sqlx), but I am not sure if that's related. I tried with the regular standard library and got the same issue.

I did see the documentation about using `nrmysql.NewConnector` instead of `mysql.NewConnector` but I'm not calling that method anywhere in my code. The only place I can find a call to that method in my code, and all of its' dependencies, is in this library.

```sh
30:// If your code is using mysql.NewConnector, simply use nrmysql.NewConnector
76:// NewConnector can be used in place of mysql.NewConnector to get an
79:	connector, err := mysql.NewConnector(cfg)
```

This happened after only changing the client, nothing else. Here is that diff:

```diff
diff --git a/cmd/serve/serve.go b/cmd/serve/serve.go
index 3b721f2..f33762f 100644
--- a/cmd/serve/serve.go
+++ b/cmd/serve/serve.go
@@ -17,6 +17,9 @@ import (
        "github.com/spf13/cobra"
        "go.uber.org/zap"
+
+       // new relic mysql client
+       _ "github.com/newrelic/go-agent/_integrations/nrmysql"
 )

 // Command contains the serve command implementation
@@ -38,7 +41,7 @@ func Command() *cobra.Command {

                        conf := database.Config(spec, nil)

-                       db, err := sqlx.Connect("mysql", conf.FormatDSN())
+                       db, err := sqlx.Connect("nrmysql", conf.FormatDSN())
                        if err != nil {
                                ctxlog.Fatal(err.Error())
                        }
```

```sh
go version go1.12.6 darwin/amd64
```

**Comment by purple4reina** [comment]
@wayneashleyberry Thanks so much for reporting this. We've been able to reproduce your issue. It seems that `mysql.NewConnector` was merged to their master branch (https://github.com/go-sql-driver/mysql/pull/941) but has not yet been officially released.

We are working to get this fixed. Again thanks for bringing this to our attention!

**Comment by purple4reina** [comment]
@wayneashleyberry Version 2.8.1 of the New Relic Go Agent has just been released with a fix to this issue.

Please be aware however that once go-sql-driver/mysql releases support for `mysql.NewConnector` we plan on adding our integration back, so please take care when upgrading our Go Agent.

I will go ahead and close this issue, however we'd love to hear from you about your thoughts on the mysql integration package! You're always welcome to re-open this issue or just leave a comment on it.

Thanks again.

**Comment by wayneashleyberry** [comment]
Thanks so much @purple4reina, I'll give it another go tomorrow 😄 I'll be upgrading `go-sql-driver/mysql` when there are new releases on my side as well, so no worries there.

**Comment by wayneashleyberry** [comment]
Updated to `v2.8.1` and boom! 💥

Thanks so much for this @purple4reina, it's working wonderfully 🥇 😄 

<img width="3198" alt="Screenshot 2019-06-19 at 08 54 41 Redacted" src="https://user-images.githubusercontent.com/727262/59747456-cfb13380-9270-11e9-8c92-114fd3bea023.png">
