### ISSUE TITLE
Grammatical error in license

### ISSUE THREAD

**Issue by DanHakimi** [newrelic/go-agent#93]
Your license here says:

> or be used for the purpose of research, reverse engineering
> or developing such competitive products, features, or software.

It appears that it should say

> or be used for the purpose of research**ing**, reverse engineering
> or developing such competitive products, features, or software.

The sentence as is does not make sense. The sentence as corrected is clear, parallel, and makes sense in the context of the license.

**Comment by willnewrelic** [comment]
Hi @DanHakimi 

We are not considering modifications to our license at this time.  The sentence as currently written reflects our intent.

**Comment by DanHakimi** [comment]
In that case, the sentence is grammatically incorrect. If your intent is actually to disallow research using the software, your license should then read:

> or be used for the purpose of research, or for reverse engineering
> or developing such competitive products, features, or software.

Either "researching, reverse engineering or developing" is the list or "research or (reverse engineering or developing)" is the list, but "research, reverse engineering, developing" is obviously not parallel, meaning that "research" must not be part of the same list as the other two, which beans that you need to separate it grammatically by something other than a single comma.

**Comment by willnewrelic** [comment]
Hi @DanHakimi 

The license changed in a recent release.  It no longer contains the sentence you are referencing.
