### ISSUE TITLE
protobuf is deprecated

### ISSUE THREAD

**Issue by amantinetti** [newrelic/go-agent#930]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

protobuf is deprecated
The package name changes from github.com/golang/protobuf to google.golang.org/protobuf
These generate problems when try to update all packages in project with newrelic agent

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

Try update packages using go get -u

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

Solve dependencies

[NOTE]: # ( Tell us what you expected to happen. )

## NR Diag results

[NOTE]: # ( Provide any other relevant log data. )

## Your Environment

Last Newrelic version

[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Reproduction case

Try to do go get -u in any project with newrelic agent

[TIP]: # ( Link a sample application that demonstrates the issue. )

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by iamemilio** [comment]
Fix is in review. Thanks for reporting.
