### ISSUE TITLE
Incompatible with Go 1.23 due to extraneous version constraint

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#939]
When attempting to compile our code with the 1.23 release candidate, we received the following error:

> github.com/newrelic/go-agent/v3/newrelic/sql_driver.go:47:37: predeclared any requires go1.18 or later (file declares //go:build go1.10)

I am unsure whether this is a bug in 1.23 or the intended behavior. Regardless, that version constraint can be removed, given that the README already says that Go 1.18+ is required.

**Comment by iamemilio** [comment]
Thanks for fixing this!
