### ISSUE TITLE
CI workflow doesn't pin 1.22

### ISSUE THREAD

**Issue by rittneje** [newrelic/go-agent#946]
#941 changed the CI matrix to test 1.20.14, 1.21, latest, 1.23rc2.

At the current moment, "latest" means 1.22.5. However, in the next few days, 1.23.0 will be released, at which point "latest" will resolve to that instead. That in turn means that 1.22 won't be tested at all until the CI workflow is explicitly changed again.

**Comment by iamemilio** [comment]
We plan to just switch versions over when the release lands. Thanks for alerting us

**Comment by rittneje** [comment]
@iamemilio reminder on this

**Comment by nr-swilloughby** [comment]
Fixed in 3.35.0
