### ISSUE TITLE
Feature request: support custom metric counters

### ISSUE THREAD

**Issue by llimllib** [newrelic/go-agent#96]
The functionality available in, for example, the .net api as: https://docs.newrelic.com/docs/agents/net-agent/net-agent-api/increment-counter ought to be supported in golang as well.

I don't believe there is any way to get custom metric counters in the current version of go-agent, am I mistaken?

**Comment by newrelic-eheinlein** [comment]
Hi @llimllib, thank you for getting us this feature request.  I would like to clarify what specifically your use case is: are you looking to increment a custom metric by 1?  If so, this is already doable by calling `app.RecordCustomMetric("metricName", 1)`.  That will increment that metric by 1.  Note, however, that the second parameter is actually a time parameter, so calling `app.RecordCustomMetric("metricName", 2)` will not increment that metric by 2 - to do that, you would need to call app.RecordCustomMetric("metricName", 1) twice.

If this satisfies your use case, please let us know - and if it doesn't, could you give us some more detail about what functionality you're looking for that is currently lacking?

**Comment by llimllib** [comment]
I believe that does the same thing as the API I pointed to.

None of the documentation suggested that it did though, so I would vote for mentioning this somewhere!

**Comment by newrelic-eheinlein** [comment]
Thank you for the feedback!  I will create an internal ticket for us to improve that documentation.
